- lib/ex_aws/dynamo/client.ex
- lib/ex_aws/dynamo/lazy.ex
- lib/ex_aws/kinesis/client.ex
- lib/ex_aws/kinesis/lazy.ex
- lib/mix/tasks/tail.ex
- test/lib/ex_aws/dynamo/integration_test.exs
> standardize streams to return bare enumerables and raise on error

- README.md
- config/test.exs
- lib/ex_aws.ex
- lib/ex_aws/client.ex
- lib/ex_aws/config.ex
- lib/ex_aws/config/auth_cache.ex
- lib/ex_aws/config/defaults.ex
- lib/ex_aws/dynamo/client.ex
- lib/ex_aws/instance_meta.ex
- lib/ex_aws/kinesis/client.ex
- lib/ex_aws/lambda/client.ex
- lib/ex_aws/s3/client.ex
- lib/mix/tasks/tail.ex
- mix.exs
- test/lib/ex_aws/config_test.exs
> Auth from Roles

- lib/ex_aws/auth.ex
- lib/ex_aws/auth/utils.ex
- test/lib/ex_aws/auth_test.exs
> [WIP] escape characters that need it when signing the path

- lib/ex_aws/dynamo/encodable.ex
- lib/ex_aws/dynamo/encoder.ex
- lib/ex_aws/dynamo/impl.ex
- test/lib/ex_aws/dynamo/encoder_test.exs
> Encoding Nested Structs

- .travis.yml
- CONTRIBUTING.md
- README.md
- lib/ex_aws/dynamo.ex
- lib/ex_aws/dynamo/client.ex
- lib/ex_aws/dynamo/impl.ex
- lib/ex_aws/kinesis.ex
- lib/ex_aws/lambda.ex
- lib/ex_aws/request/httpoison.ex
- lib/ex_aws/s3.ex
- lib/ex_aws/sqs/client.ex
- lib/ex_aws/sqs/impl.ex
- lib/ex_aws/utils.ex
- mix.exs
- mix.lock
- test/lib/ex_aws/dynamo/impl_test.exs
- test/lib/ex_aws/dynamo_test.exs
- test/lib/ex_aws/sqs_test.exs
There's some noise in the diff here because my sqs branch and yours have varying amounts of master merged in, but the gist here is that I've implemented and tested all the endpoint functions.
The tests in sqs_test.exs should make it easy to do any refactoring of the impl.ex functions. I've also manually integration tested them all against my AWS account in IEx so as long as the unit tests still pass after any changes they should still work in practice.
I haven't done anything with XML response parsing yet but thought this would be a good point to get my changes synced up with the primary SQS branch.
> Implement Endpoints

- lib/ex_aws/request.ex
> don't fail immediately on 500 errors

- lib/ex_aws/dynamo/encodable.ex
On the Enum.map/2 (line 114) the list is encoded as a generic dynamo list ([%{"S" => "abc"}, %{"N" =>  "123"}]. On the Enum.reduce/3 (line 116) the list is encoded again (line 118). The reduction happens to extract the list types which is used on the case statement (line 124) to check which dynamo list should be used.
This pull request fixes double list encoding by using a Enum.map_reduce/2 whereby the list is encoding and the list type is set: "S", "N", "B", generic ("M" or mixed values).
> Dynamo: fixed double list encoding.

- lib/ex_aws/config.ex
- mix.exs
@ericmj Using looks like
```
ExAws.S3.new(region: "us-west-1")
|> ExAws.S3.Impl.list_objects("my-bucket")
```
> derive host from region

- lib/ex_aws/dynamo/decoder.ex
- test/lib/ex_aws/dynamo/decoder_test.exs
> Dynamo decoder should handle NULL

- lib/ex_aws/config.ex
- lib/ex_aws/config/defaults.ex
- test/lib/ex_aws/config_test.exs
Hello,
Here is the PR that follows the conversation in https://github.com/CargoSense/ex_aws/issues/140
Thanks again for spending your time on this
> Allow security token config

- mix.exs
Tested using poison 2.0 didn't raise any test.
> Add support for poison 2.0

- lib/ex_aws/lambda/client.ex
- lib/ex_aws/lambda/impl.ex
Add a "qualifier" option to lambda functions. Gets set in opts, but is not added to headers (it's part of the query string).
> Add Qualifier to Lambda

- lib/ex_aws/s3/client.ex
- lib/ex_aws/s3/impl.ex
@ericmj how's this look? Fixes #75
> Add delete_all_objects

- lib/ex_aws.ex
- lib/ex_aws/config.ex
- test/lib/ex_aws/config_test.exs
- test/lib/ex_aws/s3_test.exs
> Minor fixess

- lib/ex_aws/dynamo.ex
- test/lib/ex_aws/dynamo/integration_test.exs
- test/lib/ex_aws/dynamo_test.exs
> Set key name for DeleteRequest on batch_write_item

- README.md
- lib/ex_aws/config.ex
- lib/ex_aws/config/defaults.ex
- lib/ex_aws/request.ex
No tests, but there weren't tests around this code in the first place. I did try it out on my project locally (using a `path:` dependency) and it seems to work as planned. Hope the code isn't too ugly!
Fixes #224.
> Move retry options to configuration

- lib/ex_aws/config/defaults.ex
- lib/ex_aws/operation/query.ex
- lib/ex_aws/sqs.ex
- lib/ex_aws/sqs/parsers.ex
- lib/ex_aws/utils.ex
- test/lib/ex_aws/sqs/parser_test.exs
- test/lib/ex_aws/sqs_test.exs
This fixes a bug in the list_queues function as well as adding parsing for all XML responses. 
Added unit tests for each response type, and I'll add more for errors as I encounter them.
@benwilson512
> Improvements for the SQS portion of the library

- lib/ex_aws/sns.ex
Added the ability to delete an SNS endpoint (useful if one wishes to re-assign a device token).  Already using on a production app and its working as expected. 
Thanks for making this. Its been very useful.
> Sns delete endpoint

- lib/ex_aws/sns.ex
- lib/ex_aws/sns/parsers.ex
- test/lib/ex_aws/sns/parser_test.exs
- test/lib/ex_aws/sns_test.exs
> Add parser for SNS and get_endpoint_attributes and set_endpoint_attributes endpoints

- lib/ex_aws/sns.ex
- lib/ex_aws/sns/parsers.ex
- test/lib/ex_aws/sns/parser_test.exs
- test/lib/ex_aws/sns_test.exs
This PR is based on #269, the diff will make more sense once that is merged, but I thought I'd create this anyway so I don't forget ;)
> Fix delete endpoint

- lib/ex_aws/sns.ex
- lib/ex_aws/sns/parsers.ex
- test/lib/ex_aws/sns/parser_test.exs
- test/lib/ex_aws/sns_test.exs
Adds the missing SNS API calls per #267. cc @jnicklas
> Add missing SNS API calls

- lib/ex_aws/dynamo.ex
- Undefined Dynamo.get_item!/2 fix it
> Fix document

- lib/ex_aws.ex
- lib/ex_aws/sns.ex
- lib/ex_aws/sns/parsers.ex
- lib/ex_aws/sns/public_key_cache.ex
- test/lib/ex_aws/sns/parser_test.exs
- test/lib/ex_aws/sns_test.exs
Hi @benwilson512,
Here is a initial stab at the SNS verify_message, please let me know your comments and how I should proceed with testing. Do we want to use something like Exvcr with a fixture to properly test the whole flow ?
This resolves #248
Thanks!
> Add SNS verify_message

- lib/ex_aws/config.ex
- lib/ex_aws/credentials_ini.ex
Hi,
I've noticed a few issues while trying to use the new INI file implementation.
Thanks
Nico
> Awscli credentials

- lib/ex_aws/sns.ex
- lib/ex_aws/sns/parsers.ex
- test/lib/ex_aws/sns/parser_test.exs
- test/lib/ex_aws/sns_test.exs
Adds this missing endpoint for SNS
> Add list_subscriptions_by_topic endpoint

- lib/ex_aws/config/defaults.ex
@benwilson512 Sorry I missed this one from my last PR.
> Add ap-northeast-2 s3 config

- lib/ex_aws/dynamo.ex
fix Dynamo.decode_item document.
ref #298
> fix Dynamo.decode_item document

- config/dev.exs
- config/test.exs
- lib/ex_aws/config/defaults.ex
- lib/ex_aws/operation/query.ex
- lib/ex_aws/ses.ex
- lib/ex_aws/ses/parsers.ex
- test/lib/ex_aws/ses/parser_test.exs
- test/lib/ex_aws/ses_test.exs
Hello folks,
Please, welcome SES service support. This PR introduce a very modest piece of functionality but it's just to kick-off the things.
> Add SES service support

- config/test.exs
- lib/ex_aws/config/defaults.ex
- lib/ex_aws/operation/json.ex
- lib/ex_aws/operation/query.ex
- lib/ex_aws/operation/query/parser.ex
- lib/ex_aws/operation/rest_query.ex
- lib/ex_aws/operation/s3.ex
- lib/ex_aws/parsers.ex
- lib/ex_aws/request/url.ex
- lib/ex_aws/route53.ex
- lib/ex_aws/route53/parsers.ex
- lib/ex_aws/sns/parsers.ex
- lib/ex_aws/sqs/parsers.ex
- lib/ex_aws/utils.ex
- lib/ex_aws/xml.ex
- mix.exs
- mix.lock
- test/lib/ex_aws/operation/query/parser_test.exs
- test/lib/ex_aws/parsers_test.exs
- test/lib/ex_aws/request/url_test.exs
- test/lib/ex_aws/route53/integration_test.exs
- test/lib/ex_aws/route53/parsers_test.exs
- test/lib/ex_aws/route53_test.exs
- test/lib/ex_aws/sns/parser_test.exs
- test/lib/ex_aws/sqs/parser_test.exs
- test/lib/ex_aws/utils_test.exs
- test/lib/ex_aws/xml_test.exs
- test/support/bypass_helpers.ex
- test/support/parser_helpers.ex
Hi,
Thanks a lot for your work on this project! 
I'd like to contribute with Route53 endpoints. This PR is just a single endpoint to list hosted zone and  I will push a few more later today or tomorrow. But I'd love to get your feedback on the direction I took with this implementation.
Endpoints:
- list_hosted_zones
- create_hosted_zone
- delete_hosted_zone
- change_record_sets
- list_record_sets
> Add Route53

- lib/ex_aws/sqs.ex
- lib/ex_aws/sqs/parsers.ex
- test/lib/ex_aws/sqs/parser_test.exs
- test/lib/ex_aws/sqs_test.exs
As discussed [here](https://github.com/CargoSense/ex_aws/issues/330#issuecomment-272860692).
> Add support for FIFO queues

- CONTRIBUTING.md
- README.md
- lib/ex_aws/config/defaults.ex
- lib/ex_aws/elastic_transcoder.ex
- lib/ex_aws/operation/json.ex
- test/lib/ex_aws/dynamo/integration_test.exs
- test/lib/ex_aws/dynamo_streams/integration_test.exs
- test/lib/ex_aws/elastic_transcoder/integration_test.exs
- test/lib/ex_aws/elastic_transcoder_text.exs
> Elastic transcoder

- config/dev.exs
- lib/ex_aws/ses.ex
- lib/ex_aws/ses/parsers.ex
- test/lib/ex_aws/ses/parser_test.exs
- test/lib/ex_aws/ses_test.exs
- Add SES.delete_identity function
- Add SES.set_identity_notification_topic
- Add SES.set_identity_feedback_forwarding_enabled
> Add SNS event publishing for SES

- test/lib/ex_aws/sns_test.exs
fix test calling wrong function.
https://travis-ci.org/CargoSense/ex_aws/builds/231123985?utm_source=github_status&utm_medium=notification
> fix test typo

- CONTRIBUTING.md
- README.md
- lib/ex_aws/cloudwatch.ex
- lib/ex_aws/cloudwatch/parsers.ex
- lib/ex_aws/config/defaults.ex
- test/lib/ex_aws/cloudwatch/integration_test.exs
- test/lib/ex_aws/cloudwatch/parser_test.exs
- test/lib/ex_aws/cloudwatch_test.exs
Hi,
we are using this library for one of our projects and we needed to add support for Cloudwatch DescribeAlarms. 
Feel free to merge if it's useful. 
Thanks for the library
andrea
> Add cloudwatch describe alarms

- mix.exs
> Add Hackney 1.8.6 to the dependency specification

- lib/ex_aws/cloudformation.ex
- lib/ex_aws/ec2.ex
- test/lib/ex_aws/cloudformation_test.exs
- test/lib/ex_aws/ec2_test.exs
-Fixed parameters allowed to pass in for a few of the API operations.
-Updated to use version 2016.11.15 for AWS EC2
-Refactored the code heavily
-Added a bunch more tests
-Added docs for the EC2 Module with examples for each of the different API endpoints
-Made sure the API operations work or the results of query matches AWS' doc.
> Fixed a lot of the EC2 API Operations

- lib/ex_aws/sns.ex
- lib/ex_aws/sns/parsers.ex
- test/lib/ex_aws/sns_test.exs
https://docs.aws.amazon.com/sns/latest/api/API_ListEndpointsByPlatformApplication.html
Support for Lists the endpoints and endpoint attributes for devices in a supported push notification service.
> Add SNS ListEndpointsByPlatformApplication

- README.md
Make it easier for new users to know the current version and find the documentation using two new badges.
> Add hex.pm and documentation badge

- lib/ex_aws/request.ex
How can this be tested?
Related to #358
> Accept 304 response as success

- README.md
Add to the README an example of configuring the region.
> Show configuring the region

- priv/endpoints.exs
> Add secrets manager to endpoints

- lib/ex_aws/auth.ex
Currently if you sign an upload URL with ex_aws_s3 that includes query params the query params will be passed in the url but not signed. This means that the actor that receives the url could modify anything in the query params and S3 will accept them. Example:
```
{:ok, url} = ExAws.S3.presigned_url(config, :put, "my_bucket", "foo.jpg", [query_params: [{"content-type", "image/jpeg"}]])
curl -I -XPUT -H "Content-Type: image/png" -T './foo.png' url
200 OK
```
> Make headers signed to prevent tampering

- LICENSE
This will indicate in the github UI that the project is MIT licensed with an icon.
> Add LICENSE file for github integration

- mix.exs
- mix.lock
Related to this issue: https://github.com/ex-aws/ex_aws/issues/575
> Removed xml_builder dependency from ex_aws

- lib/ex_aws/operation/query.ex
Hello!
I need this functionality for CloudWatch PutMetricData API. It has 40KB limit on the payload size but allows GZIP compression to fit bigger payloads.
PR to `ex_aws_cloudwatch` is coming.
> Support content-encoding in ExAws.Operation.Query

- README.md
I was seeing the same Poison-related errors as #632 but it wasn't immediately clear what to do about it.  Thanks!
> Add json_codec configuration example

- priv/endpoints.exs
- according to https://docs.aws.amazon.com/general/latest/gr/rande.html
> Cloud Map: expanded available Endpoints

- priv/endpoints.exs
reference: https://docs.aws.amazon.com/general/latest/gr/rande.html
> Adding ap-east-1 region

- priv/endpoints.exs
Hi folks, was getting an error trying to generate presigned urls to make sagemaker requests. This seems to fix it. Thanks!
> add sagemaker to govcloud

- priv/endpoints.exs
Update the available SES endpoints based on [https://docs.aws.amazon.com/ses/latest/DeveloperGuide/regions.html](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/regions.html).
> Update available SES endpoints.

- priv/endpoints.exs
Updated the available Textract endpoints based on https://docs.aws.amazon.com/general/latest/gr/textract.html
> Updating available Textract endpoints.

- priv/endpoints.exs
https://docs.aws.amazon.com/general/latest/gr/ses.html
> Add eu-west-2 email endpoint

- priv/endpoints.exs
https://docs.aws.amazon.com/general/latest/gr/fh.html
> Add ca-central-1 firehose endpoint

- priv/endpoints.exs
We are trying to use firehose for eu-west-3 (Paris) but without being added we get an exception.
> Add eu-west-3 (Paris) to firehose

- priv/endpoints.exs
Added ca-central-1, sa-east-1 and replaced ap-southeast-1 with ap-southeast-2
> Fixed email endpoint regions

- README.md
- lib/ex_aws.ex
- lib/ex_aws/config/auth_cache.ex
- lib/ex_aws/json/codec.ex
- lib/ex_aws/operation.ex
- lib/ex_aws/request.ex
- lib/ex_aws/request/hackney.ex
- lib/ex_aws/request/http_client.ex
- lib/mix/tasks/tail.ex
- mix.exs
List of changes:
- Use common source url
- Add new maintainer
- Remove duplicate page title
- Word wrapping
- Badges and more badges!
- Update example code styling
> Misc HTML doc generation changes

- priv/endpoints.exs
https://docs.aws.amazon.com/general/latest/gr/comprehend.html
> Add comprehend endpoint

- priv/endpoints.exs
* Added sa-east-1 region to cognito-idp service
> Add sa-east-1 region to cognito-idp service

- priv/endpoints.exs
List compiled according to AWS QuickSight availability in [regions]
[regions]: https://docs.aws.amazon.com/quicksight/latest/user/regions.html
> Add QuickSight endpoints

- lib/ex_aws/operation/s3.ex
- test/ex_aws/operation/s3_test.exs
Second attempt for https://github.com/ex-aws/ex_aws/pull/783
> Ensure absolute path for virtual hosted style S3 urls

- priv/endpoints.exs
Update regions for SageMaker runtime endpoint as per https://docs.aws.amazon.com/general/latest/gr/sagemaker.html
> Update regions for SageMaker runtime endpoint

- priv/endpoints.exs
Updating the regions under SES (mail) as per the latest docs - https://docs.aws.amazon.com/general/latest/gr/ses.html
> Update regions for SES (mail)

- README.md
> Update README.md to document Session Token support

- lib/ex_aws/config.ex
> Show docs for `ExAws.Config`

- priv/endpoints.exs
Taken from https://docs.aws.amazon.com/general/latest/gr/transcribe.html
> Add all supported regions for transcribe

- lib/ex_aws/operation/s3.ex
- test/ex_aws/operation/s3_test.exs
Attempting to address the request here: #770 
This could also go somewhere in `ExAws.S3`. Happy to amend the error itself and its message to something more idiomatic to the project if necessary.
> Raise when no bucket is available

- lib/ex_aws/request/http_client.ex
> Enhance HTTP methods support docs

- lib/ex_aws/config/defaults.ex
- lib/ex_aws/instance_meta.ex
- test/ex_aws/instance_meta_test.exs
> make imds v2 optional

- lib/ex_aws/config/auth_cache.ex
Closes #798 
As described on the issue, when an error happens when retrieving credentials, the error itself is stored on the auth cache, which results in weird errors happening on subsequent calls.
In order to not make extensive changes but still make the library more resilient, a simple retry algorithm is introduced:
* 30 second window till next credentials refresh is divided into 6 blocks of 5 seconds.
* On each block, a node will wait from 0 to 5 seconds till it retries the auth request
* If after the threshold nodes haven't been able to refresh the credentials successfully, an error is raised
This implementation doesn't include any breaking changes to the current API.
We were experiencing the issue happening on #798 every other day, and after running this patch, we haven't seen it …
> Improve resiliency on auth adapter when transient errors happen

- lib/ex_aws/credentials_ini/file.ex
> Fix SSO error for non-SSO regions

- priv/endpoints.exs
Adds support to EKS, allowing to create operations like:
```
data = %{scalingConfig: %{desiredSize: replicas}}
operation = %ExAws.Operation.JSON{
http_method: :post,
path: "/clusters/#{cluster()}/node-groups/#{node_group()}/update-config",
data: data,
service: :eks
}
```
> Add EKS support

- .github/workflows/on-push.yml
- lib/ex_aws/operation/json.ex
- lib/ex_aws/operation/query.ex
- lib/ex_aws/operation/rest_query.ex
- lib/ex_aws/operation/s3.ex
- lib/ex_aws/request.ex
- lib/ex_aws/utils.ex
- mix.exs
> Add operation error_parser

- .github/dependabot.yml
- .github/workflows/on-push.yml
Remove the extra redirection. See https://github.com/erlef/setup-beam/issues/20
Prettied by `prettier -w .github/`
> Use erlef/setup-beam and prettify yaml files

- priv/endpoints.exs
Add support for Jakarta region.
> Add Jakarta region in partitions

- priv/endpoints.exs
sqs is available in af-south-1
> Add af-south-1 to sqs endpoints

- priv/endpoints.exs
https://github.com/ex-aws/ex_aws/issues/971
> Add af-south-1 to KMS.

- priv/endpoints.exs
> feature: eu-central-2 support for S3

- priv/endpoints.exs
Add the OpenSearch Servelerss service to the endpoints list.
This closes #1034
> Add `aoss` to endpoints.exs

- priv/endpoints.exs
Add the [AWS Data Exports](https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/Welcome.html#Welcome_AWS_Billing_and_Cost_Management_Data_Exports) to the endpoints list.
> add `bcm-data-exports` to endpoints.exs

- mix.exs
This adds the changelog to the package files, so that it is visible in hex diff.
> add changelog to package files

- priv/endpoints.exs
https://docs.aws.amazon.com/location/latest/developerguide/location-regions.html
as of 2024-04-11
> Update locations regions to match documented regions

- priv/endpoints.exs
Endpoints and regions as listed at https://docs.aws.amazon.com/general/latest/gr/pinpoint.html.
---
> Add regions and endpoints for the Pinpoint `mobiletargeting` service

- priv/endpoints.exs
Endpoints listed in:
https://docs.aws.amazon.com/general/latest/gr/ev_pipes.html
> Add support for EventBridge Pipes service

- priv/endpoints.exs
> Add some endpoints per @acrolink's requests

- CHANGELOG.md
- mix.exs
- priv/endpoints.exs
> Fix us-west-1 and us-west-2 for pinpoint endpoints

- priv/endpoints.exs
> feature: eu-central-2 support for EC2

- lib/ex_aws/request/req.ex
- priv/endpoints.exs
Closes #1087
This is my first PR ever!
> Rename follow redirect in Req adapter

- mix.exs
> Do not warn when optional deps are not available

- .github/workflows/on-push.yml
- .tool-versions
> Support OTP 28 in CI and asdf
