- .travis.yml
- CONTRIBUTING.md
- mix.exs
- mix.lock
Tests should run and pass now on travis provided you enter the aws credential environment variables in the travis UI.
Tests passed in Erlang 18.0 / 17.5 / 17.1 in travis on my account. I added 17.5 since that was the most recent 17.x release but left 17.1 since that's what you had configured previously, feel free to add / remove versions to test as you see fit.
Also added a blurb to CONTRIBUTING.md with instructions for getting tests passing locally. Note that we'll probably need to tweak the IAM example as tests are added for services in the future though.
> erlang 18 compatibility / get travis-ci working

- lib/ex_aws/dynamo/encodable.ex
- test/lib/ex_aws/dynamo/encoder_test.exs
> use String.Chars for float to get a more ordinary value

- lib/ex_aws/auth.ex
- lib/ex_aws/auth/utils.ex
- lib/ex_aws/s3/client.ex
- lib/ex_aws/s3/impl.ex
- lib/ex_aws/s3/request.ex
- test/lib/ex_aws/auth_test.exs
- test/lib/ex_aws/s3_test.exs
Hi Ben,
this is a very early phase PR (i.e. I am not done yet). I'd very much like to get some early feedback from you before I proceed.
My initial idea was to change as little as possible from the existing code, simply add on. But then I found that `auth.ex` had a lot of bits and pieces of what I needed, so I was kind of forced to refactor it to avoid duplication. I hope you are OK with this.
I have not tested this, not even manually, I just got it to a state where it compiles and looks like it could work. I will probably continue tomorrow. But I just would like to get a thumbs up or thumbs down from you in regards to what I have done so far.
I also have a question for you: I see that function `ExAws.S3.Request.url` is used to construct S3 URLs. At first I thought I could use it, but …
> Implement S3 presigned_url API function

- lib/ex_aws/actions.ex
- lib/ex_aws/sqs/impl.ex
- lib/ex_aws/utils.ex
I was playing with exrm releases earlier today and noticed that my app was blowing up when I tested a release locally because Mix.Utils.camelize was undefined. I asked about it in irc and tristan__ & scrogson let me know that ExAws shouldn't be using be using mix functions at runtime. The issue could be resolved by adding :mix to my applications so it would get bundled in the release but the consensus seemed to be that mix is a build tool and shouldn't need to be bundled at runtime.
I've ported the Mix.Utils.camelize function to ExAws.Utils to remove the need for mix at runtime.
> remove runtime dependency on Mix

- lib/ex_aws/sqs/request.ex
- mix.exs
- mix.lock
Useful for using tools like https://github.com/iain/fake_sqs for the dev environment, just duplicated what you did for the dynamodb request.ex
The mix.lock change happened when I ran mix deps.get on a fresh clone of ex_aws ¯\\\_(ツ)_/¯
> Allow specifying a port for SQS

- lib/ex_aws/auth.ex
- lib/ex_aws/sns/request.ex
SNS publish was failing when there were spaces in the JSON as they were being incorrectly encoded as `+` instead of `%20`. Also, tilde should not be encoded.
> Use percent encoding for canonical query strings, per AWS docs

- lib/ex_aws/s3/impl.ex
ExAws must not force the `http` scheme for S3 urls when using `virtual_host: true`.
AWS fully supports serving objects via HTTPS with virtual hosts.
In fact, some regions (notably Oregon) **require** the virtual_host format if you attempt to use the path-based format. So ExAws currently cannot produce a valid https url for Oregon buckets at all.
Example of a bucket object which requires virtual host: https://s3.amazonaws.com/dev-sched-oregon/arctest/uploads/image.png
The only caveat (which I assume this logic was trying to fix initially) is if you create a bucket which is **not** DNS compliant.  However, this is thoroughly documented throughout AWS's documentation.
> When using virtual hosted–style buckets with SSL, the SSL wild card certificate only matches buckets that do not contain …
> Don't force http scheme when using virtual host

- mix.exs
thix pr fixes s3 ap-northeast-1's endpoint.
before
```
iex(1)> ExAws.S3.new(region: "ap-northeast-1")
%ExAws.S3{config: %{access_key_id: "XXXXXXXXXXXXXXX", debug_requests: true,
host: "s3-ap-southeast-1.amazonaws.com", # FIX HERE !
http_client: ExAws.Request.HTTPoison, json_codec: Poison,
region: "ap-northeast-1", scheme: "https://",
secret_access_key: "XXXXXXXXXXXXXXX"}, service: :s3}
iex(2)>
```
after
```
iex(1)> ExAws.S3.new(region: "ap-northeast-1")
%ExAws.S3{config: %{access_key_id: "XXXXXXXXXXXXXXX", debug_requests: true,
host: "s3-ap-northeast-1.amazonaws.com", # FIXED !
http_client: ExAws.Request.HTTPoison, json_codec: Poison,
region: "ap-northeast-1", scheme: "https://",
secret_access_key: "XXXXXXXXXXXXXXX"}, service: :s3}
iex(2)>
```
> fix s3 ap-northeast-1's endpoint

- lib/ex_aws/s3/impl.ex
@benwilson512 S3 requires a "Content-MD5" field in the header for "Delete Multiple Objects" operation, and it currently seems to be missing.
> Add MD5 to header for delete_multiple_objects

- lib/ex_aws/s3/parsers.ex
- test/lib/ex_aws/s3/parser_test.exs
This PR extends the S3 parser to include CommonPrefixes when listing objects
Thanks!
> S3: Added parsing for CommonPrefixes when listing objects

- lib/ex_aws/s3/impl.ex
Warning: crypto:md5/1 is deprecated and will be removed in in a future release; use crypto:hash/2
> Switch to using :crypto.hash/2 to remove deprecation warning

- lib/ex_aws/request/httpotion.ex
The last two args in ExAws.Request.HTTPotion.request/4 should be optional as per the HTTPoison adapter.
> Fixes ExAws.Request.HTTPotion.request/4

- lib/ex_aws/kinesis/request.ex
Hi there,
I've been using [kinesalite](https://github.com/mhart/kinesalite) as a mock server to test the application I am writing. Even though I could have config kinesalite to set the port to to the default one, I think that having an option to explicitly set the port is a good idea, as the [dynamodb request module](https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/dynamo/request.ex#L22-L28) is already doing.
Also, I didn't see any particular test I could verify this new changes. Maybe it wouldn't be a bad idea to refactor the request modules (now the dynamodb module and the kinesis module are almost 100% the same) and some test to it. I might be able to help if needed.
Thanks!
> Add port option to kinesis config

- lib/ex_aws/s3/parsers.ex
- test/lib/ex_aws/s3/parser_test.exs
Hi! Thanks for the awesome library! I tried out `ExAws` for the first time tonight and ran into a small issue when attempting to list the objects in one of our companies' S3 buckets. I had been able to list buckets without issue using `ExAws.S3.list_buckets/0`, but the following failed:
``` elixir
iex> ExAws.list_objects("my-bucket-name")
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
stacktrace:
(elixir) lib/enum.ex:1: Enumerable.impl_for!/1
(elixir) lib/enum.ex:116: Enumerable.reduce/3
(elixir) lib/enum.ex:1486: Enum.reduce/3
(elixir) lib/enum.ex:1025: Enum.into/4
(ex_aws) lib/ex_aws/s3/parsers.ex:41: anonymous fn/1 in ExAws.S3.Parsers.list_objects_binaries/1
(elixir) lib/enum.ex:1019: anonymous fn/4 in Enum.into/3
(stdlib) lists.erl:1262: :lists.foldl/3 …
```
> Allow ExAws.S3.Client.list_objects to handle unowned objects

- lib/ex_aws/config.ex
Following the discussion in https://github.com/CargoSense/ex_aws/issues/90
This PR removes the `{:host, host}, config ->` clause from `retrieve_runtime_config/2` to be able to set the host value within an ENV variable and be able to use `host: {:system, "AWS_HOST"}` in the `config*.exs`
I don't see any reason to keep this clause, but I just started using your project, so maybe this PR is a bit too rash.
At least it opens the discussion on this matter, since i'm stuck if i don't do this modification, and i'm obviously not fond to keep working with a fork to be able to use it.
> Be able to use ENV variables to define host parameter

- lib/ex_aws/sns.ex
- test/lib/ex_aws/sns_test.exs
When I tried to use `SNS.publish/2` with the latest version, I got the following error.
```
{:error, {:http_error, 400, "<ErrorResponse xmlns=\"http://webservices.amazon.com/AWSFault/2005-15-09\">\n  <Error>\n    <Type>Sender</Type>\n    <Code>InvalidAction</Code>\n    <Message>Could not find operation publish for version 2010-03-31</Message>\n  </Error>\n  <RequestId>xxxx</RequestId>\n</ErrorResponse>\n"}}
```
So, I've fixed this issue, and added some brief tests.
> Fix 'could not find operation' error on SNS.

- CONTRIBUTING.md
"This policy contains the following JSON error on line 11: Unexpected ']'"
> Fix syntax error in sample IAM policy

- lib/ex_aws/request.ex
I implemented exponential backoff with jitter based on the "full jitter" variant of the formula described at https://www.awsarchitectureblog.com/2015/03/backoff.html
The article didn't specify values for the @max_backoff_in_ms or @base_backoff_in_ms values. I picked 10 seconds for the max because that is how long the longest retry would be for the 10th attempt currently in master, and I chose 10ms for the base because that value resulted in a cap of around 10 seconds on the 10th attempt. Feel free to fiddle with those or with the formula.
sleep times between requests with this formula and base / max values are as follows:
attempt # | between 0 and x ms
----------|----------------------
1 | 20
2 | 40
3 | 80
4 | 160
5 | 320
6 | 640
7 | 1280
8 | 2560
9 | 5120
10 | 10000
Thanks!
Adam
> make retry backoff exponential with jitter

- lib/ex_aws/auth.ex
- lib/ex_aws/s3.ex
- test/lib/ex_aws/auth_test.exs
- test/lib/ex_aws/s3_test.exs
Added an optional :query_params field to presigned_url_opts
If this is set to an array of key value pairs [{"key", "value}], then those are added to the url to be signed and included in the calculated signature. This is required to enable uploading parts of a multipart upload directly from the browser to S3.
Added tests to s3_test.exs and auth_test.exs and explained it in the docs for presigned_url.
> Add support for additional query parameters to S3.presigned_url

- lib/ex_aws/json/codec.ex
- lib/ex_aws/json/jsx.ex
- mix.exs
return proper error tuples from `encode/1` and `decode/1` and take advantage of jsx support for maps
> improve jsx.ex

- lib/ex_aws/auth.ex
- lib/ex_aws/auth/credentials.ex
- lib/ex_aws/auth/signatures.ex
- test/lib/ex_aws/auth/credentials_test.exs
- test/lib/ex_aws/auth/signatures_test.exs
I am working on adding S3 presigned post functionality (#114) and found it a little confusing how the actual signature was being generated. I extracted an `ExAws.Auth.Signatures` module to make this more clear, and so I can share this functionality with the PresignedPostGenerator module I'm working on.
> Extracted Auth.Signatures into separate module

- lib/ex_aws/auth.ex
- lib/ex_aws/auth/credentials.ex
- test/lib/ex_aws/auth/credentials_test.exs
I just realized right after you committed #214, the argument order of functions in the `Credentials` module don't match the argument order in the `Signatures` module.
Here are how they are currently
```elixir
Credentials.generate_credential_scope_v4(service, datetime, config)
Signatures.generate_signature_v4(service, config, datetime, string_to_sign)
```
This change updates the argument order of functions in the `Credentials` module to match the argument order of functions in the `Signatures` module.
```elixir
Credentials.generate_credential_scope_v4(service, config, datetime)
Signatures.generate_signature_v4(service, config, datetime, string_to_sign)
```
Sorry about this oversight.
> Update Credentials functions arg order to match Signatures arg order

- lib/ex_aws/sns.ex
- test/lib/ex_aws/sns_test.exs
SNS has a couple of endpoints so you can use it to send push notifications to mobile devices and this PR adds support for that. I had trouble running the full test suite but `mix test test/lib/ex_aws/sns_test.exs` runs fine with no errors.
> Add application platform support to SNS

- lib/ex_aws/operation/rest_query.ex
- test/lib/ex_aws/ec2/integration_test.exs
I want to get the result of EC2-API running such code.
```
ExAws.EC2.describe_instances
|> ExAws.request
```
so, implementation of the ExAws.Operation Protocol to ExAwsOperation.RestQuery.
> Implement ExAws.Operation, for ExAws.Operation.RestQuery

- CONTRIBUTING.md
In order to in pass the `test/lib/ex_aws/ec2/integration_test.exs`  of TravisCI, 
you need to add the EC2 of the policy to the IAM.
Can you add the policy of EC2 to IAM that are used in TravisCI?
> Add a policy of ec2 in order to pass the ec2-integration-test

- lib/ex_aws/auth.ex
- test/lib/ex_aws/auth_test.exs
Fix some issues in generating process of presigned url
Summary
* Remove unnecessary url encoding/decoding
* No need to replace "+" to " "
* Use canonical query in both query to sign and query of result `presigned_url`
* Keep ordering of original query in presigned url
* Update test cases
* expected `X-Amz-Signature`s are calculated by using https://github.com/kenrota/scriptbox/blob/master/ruby/gen_presigned_url_base_on_aws_example.rb
> Fix some issues in generating process of presigned url

- lib/ex_aws/config/defaults.ex
Remove `AWS_SECURITY_TOKEN` from common setting, because that is optional setting.
> Remove `AWS_SECURITY_TOKEN` from common setting

- lib/ex_aws/sns.ex
As per AWS SNS [API docs](http://docs.aws.amazon.com/sns/latest/api/API_Publish.html), you can specify PhoneNumber as a request parameter; provided you don't specify :target_arn or :topic_arn. 
This allows for the sending of SMS on a one-time basis rather than to subscribers of a particular topic (useful for sending one-time access codes etc).
Whilst the code still executes without this change, it should probably be made to clarify the options that `publish_opts` has, and should help towards breaking changes in the future.
Tests are passing as before.
> Added :phone_number to SNS publish_opts & updated spec.

- lib/ex_aws/sns.ex
Current SNS message_attributes struct only accepts strings representing the type, rather than atoms. Not sure if this is intended behaviour or not but it seems odd.
> SNS message_attributes struct should accept atoms representing type

- lib/ex_aws/sqs.ex
- lib/ex_aws/sqs/parsers.ex
- test/lib/ex_aws/sqs/parser_test.exs
- test/lib/ex_aws/sqs_test.exs
SQS has the concept of Attributes *and* MessageAttributes. Attributes
are intrinsic to a message, and are set by the system.
MessageAttributes, however are set by the user and can be
anything.
This PR adds support for getting and setting message attributes, and can
parse numeric, binary and string attributes.
@benwilson512
> Handled Message Attributes

- lib/ex_aws/sqs/parsers.ex
- test/lib/ex_aws/sqs/parser_test.exs
Something changed and caused the error shape to change, which broke the
error parsers.
We should figure out how to prevent regressions like this in the future.
@benwilson512
> Fixed error parsing

- lib/ex_aws/sqs/parsers.ex
- test/lib/ex_aws/sqs/parser_test.exs
If multiple messages are requested, the response contains the key
`:messages`, which contains a list of the messages. If one is requested,
the response contains the `:message` key.
@benwilson512, I'm not sure how I feel about changing the key based on the number of messages returned. Thoughts appreciated.
> Handled multiple messages from receive_message

- lib/ex_aws/s3/upload.ex
Fix it.
```shell
warning: variable v is unused
lib/ex_aws/s3/upload.ex:69
```
> Fix warning

- config/dev.exs
- config/test.exs
- lib/ex_aws/config/defaults.ex
- lib/ex_aws/dynamo_streams.ex
- test/lib/ex_aws/dynamo_streams/integration_test.exs
- test/lib/ex_aws/dynamo_streams_test.exs
Contains an implementation of the DynamoDB Streams API based on http://docs.aws.amazon.com/dynamodbstreams/latest/APIReference/API_Operations.html. There are integration tests included that run against local dynamodb.
> implement dynamodb streams

- README.md
- lib/ex_aws/instance_meta.ex
Hi,
I've added support for looking up task role credentials when using ECS (taskRoleArn in the task definition) which overwrites the instance role.
Thanks
> Added support for ECS task role credentials

- lib/ex_aws/kms_client_encryption.ex
Hi
The new module makes it easy to use KMS for client side encryption/decryption
```elixir
message = "waffles"
assert ExAws.KMS.ClientEncryption.encrypt(message, key_id) |> ExAws.KMS.ClientEncryption.decrypt == message
```
Any suggestion on how to write tests given the dependency on a valid master key?
Thanks
> Added module for client side KMS encryption

- lib/ex_aws/instance_meta.ex
this was broken in #294 
```
** (exit) :badarg
(kernel) gen_tcp.erl:148: :gen_tcp.connect/4
(hackney) src/hackney_connect.erl:246: :hackney_connect.do_connect/5
(hackney) src/hackney_connect.erl:37: :hackney_connect.connect/5
(hackney) src/hackney.erl:328: :hackney.request/5
(ex_aws) lib/ex_aws/request/hackney.ex:20: ExAws.Request.Hackney.request/5
(ex_aws) lib/ex_aws/instance_meta.ex:18: ExAws.InstanceMeta.request/2
(ex_aws) lib/ex_aws/instance_meta.ex:36: ExAws.InstanceMeta.instance_role_credentials/1
```
> fix iam role detection in EC2

- lib/ex_aws/config/defaults.ex
- lib/ex_aws/credentials_ini.ex
Looking at the discussion on #245 I think the intention was for configparser_ex to be optional, but with the `raise` blocks and the addition of the `:awscli` to the default config resolution list you'll always get an error before attempting to retrieve ec2 credentials.
also fixed an unused variable warning.
> Remove configparser_ex requirement in ec2 environments

- mix.exs
> use parentheses to remove the ambiguity in mix.exs

- mix.exs
`SweetXml` version `~> 0.5` doesn't seem to have the method `transform_by` anymore (probably had at some point). That's the method some parsers are referring to: 
https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/sqs/parsers.ex#L59
Version `~> 0.6` has it though
> Update SweetXml version

- lib/ex_aws/sns.ex
- mix.lock
- test/lib/ex_aws/sns_test.exs
AWS expects MessageAttributes, as a list, to be formatted like so:
```
"MessageAttribute.entry.1.Name" => "value"
```
SNS currently formats attributes without "entry" and with 0 indexing:
```
"MessageAttribute.0.Name" => "value"
```
This results in the following error when you try to publish a message
with MessageAttributes:
```
{:error,
{:http_error, 400,
%{code: "MalformedInput", detail: "",
message: "Top level element may not be treated as a list",
request_id: "3fc49509-919d-57a3-8147-c5faf4348859", type: "Sender"}}}
```
This has already been fixed elsewhere. See the following examples:
- https://github.com/CargoSense/ex_aws/blob/7082f43acabf283d2e98673ee080e9122c737b97/test/lib/ex_aws/sns_test.exs#L40-L41
- https://github.com/CargoSense/ex_aws/blob/7082f43acabf283d2e98673ee080e9122c737 …
> Properly format SNS MessageAttributes

- lib/ex_aws/dynamo.ex
These types should be used `map()`.
[Map specification](https://hexdocs.pm/elixir/typespecs.html#types-and-their-syntax):
> Notice that the syntactic representation of map() is %{optional(any)
> => any}, not %{}. The notation %{} specifies the singleton type for
> the empty map.
> fix type mismatch in dynamo.ex.

- config/dev.exs
- config/test.exs
- lib/ex_aws/auth.ex
- lib/ex_aws/config/defaults.ex
- lib/ex_aws/dynamo_streams.ex
- test/lib/ex_aws/dynamo_streams/integration_test.exs
Attempt 2, this time it actually works 🙁.
Dynamo Streams uses the "dynamodb" service name for the signing of all of the operations, but requires a different URL. Rather than trying to hack something into the `:dynamodb` config key I added a `:service_override` config option... it's not super elegant, I'm certainly open to suggestions on improving this.
I've added a `list_streams` call that hits live aws from the integration test and have tested the remaining operations against real streams now.
> Dynamo streams implementation

- lib/ex_aws/config/defaults.ex
I checked the list and this seems to be the only one that's missing. Coincidentally, it's the region I was trying to use for my project 😝 
http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region
> Add us-east-2 region & endpoint to S3 options

- lib/ex_aws/s3.ex
The type specification for presigned_url_opts was making dialyzer complain about valid values. This change corrects it.
> Fix presigned_url_opts type

- lib/ex_aws/s3.ex
- test/lib/ex_aws/s3_test.exs
For whatever reason, AWS doesn't want anything sent up when creating a
bucket in the "default" region, us-east-1. This ensures that we send up
an empty body whenever creating a bucket in that region.
Relevant AWS documentation here:
http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUT.html#RESTBucketPUT-requests-examples
This took me entirely too long to realize.. here are the relevant requests with some ids/hashes removed:
```
iex(4)> ExAws.S3.put_bucket("paired.photos", "") |> ExAws.request!(debug_requests: true)
[debug] Request URL: "https://s3.amazonaws.com/paired.photos/"
[debug] Request HEADERS: [{"Authorization", "AWS4-HMAC-SHA256 Credential=REMOVED/20170206/us-east-1/s3/aws4_request,SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date,Signature=REMOVED"}, …
```
> Fix S3 bucket creation for the us-east-1 region

- lib/ex_aws/s3.ex
Problem: The `acl_opts` type is used in two places ([1](https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/s3.ex#L639), [2](https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/s3.ex#L674)) extending another union type of possible list item types. Putting this type in a list itself is incorrect, as it would lead to code like: `put_object('bucket', 'path', 'content', [[{:acl, :public_read}]]` which fails immediately in [`put_object_headers/1`](https://github.com/CargoSense/ex_aws/blob/e465e3241d04cbe083ff9f4478c9ac050feccca7/lib/ex_aws/s3/utils.ex#L12).
Solution: Define `acl_opts` as a union type of two item tuples and define list variants in those specific type specs.
> Update acl_opts to a union type of two item tuples

- lib/ex_aws/s3/parsers.ex
function ` ExAws.S3.Parsers.parse_list_multipart_uploads ` cannot access from s3.ex because this function is not exported.
at s3.ex:271
> add export module S3.parsers.parse_list_multipart_uploads

- lib/ex_aws/s3/parsers.ex
- lib/ex_aws/sqs/parsers.ex
Could have saved me quite some time because the error was very confusing. It's easy to miss the fact that the parsing functions are not compiled when the parser is missing..
> Raise meaningful error when xml parser is missing

- lib/ex_aws/request/url.ex
- test/lib/ex_aws/request/url_test.exs
When the port is provided via an environment variabe it will come in as
a string, e.g.
```ex
config :ex_aws, :s3,
scheme: {:system, "S3_SCHEME"},
host: {:system, "S3_HOST"},
port: {:system, "S3_PORT"}
```
`URI.to_string/1` expects port to be an integer or else it will raise.
This PR makes sure we perform that conversion if necessary to prevent
this exception
> extend ExAws.Request.Url to handle stringified port

- lib/ex_aws/ec2.ex
- test/lib/ex_aws/ec2/integration_test.exs
- test/lib/ex_aws/ec2_test.exs
As discussed in https://github.com/CargoSense/ex_aws/issues/241, the filter implementations on the describe methods do not work correctly.
Since I need `describe_tags` I started with that one, and if this looks good I can implement changes in other methods. I borrowed inspiration from JS SDK 
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2.html#describeTags-property
> Fix EC2 filter implementations

- lib/ex_aws/sns.ex
- lib/ex_aws/sns/parsers.ex
- test/lib/ex_aws/sns/parser_test.exs
- test/lib/ex_aws/sns_test.exs
This pr adds both `list_phone_numbers_opted_out` and `opt_in_phone_number` to the `SNS` module.
Also corrected api url for sns documentation which was directing to a 'Looking for Something?' page.
API Docs:
http://docs.aws.amazon.com/sns/latest/api/API_ListPhoneNumbersOptedOut.html
http://docs.aws.amazon.com/sns/latest/api/API_OptInPhoneNumber.html
> add ListPhoneNumbersOptedOut and OptInPhoneNumber to SNS

- lib/ex_aws/ses.ex
- test/lib/ex_aws/ses_test.exs
This PR adds the ListIdentities call to the SES module. It is almost
identical to `list_configuration_sets` only that it has an additonal
optional parameter for specifying `IdentityType`
API Docs: http://docs.aws.amazon.com/ses/latest/APIReference/API_ListIdentities.html
> Add ListIdentities call to SES

- lib/ex_aws/operation/s3.ex
- corrects internal nomenclature: `files` → `objects`
- adds missing `:service` key
- addresses #404
> fixes ExAws.Operation.S3DeleteAllObjects

- lib/ex_aws/dynamo.ex
attribute_type seems to have been replaced by key_type, and the 'email' attribute is required in your attribute definitions for the base table.
HTH
Thanks
A
> Updated Dynamo create_table example.

- lib/ex_aws/auth/utils.ex
Not sure if there is a preference for piping to String.downcase, but Base.encode16 has a :case option for this:
```elixir
Base.encode16(case: :lower)
```
> use Base.encode16 :case option instead of piping to String.downcase

- lib/ex_aws/ec2.ex
- test/lib/ex_aws/ec2_test.exs
The change from `:instances` to `:instance_id` in `describe_instances/1` and `describe_instance_status/1` are breaking, but they have never worked correctly in a released version so I think it's better to remove the special handling and standardize them with the AWS API parameter name.
This will support syntax like `instance_id: ["instance1", "instance2"]` but won't work with `instance_id: "instance1", instance_id: "instance2"`. I don't see a way to support the second one without adding a second iteration through the parameter list in `normalize_opts/1`, I'm not sure what the preference is for performance vs convenience (the typespec only shows the supported syntax).
This addresses #411
> fix ec2 list-based parameters

- lib/ex_aws/sqs/parsers.ex
- test/lib/ex_aws/sqs/parser_test.exs
- https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessageBatch.html#API_SendMessageBatch_ResponseElements
- https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_BatchResultErrorEntry.html
References:
- https://boto3.readthedocs.io/en/latest/reference/services/sqs.html#SQS.Client.send_message_batch
- https://github.com/boto/boto/blob/master/boto/sqs/batchresults.py
- https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-sqs/source/model/BatchResultErrorEntry.cpp
- https://github.com/aws/aws-sdk-go/blob/0bc99f4aa1cf50245de234b1ce0b33463a3ad5fe/service/sqs/api.go#L3689
> [sqs] Add parsing for error entries in SendMessageBatch response

- lib/ex_aws/ses.ex
- lib/ex_aws/ses/parsers.ex
- test/lib/ex_aws/ses/parser_test.exs
- test/lib/ex_aws/ses_test.exs
API docs: http://docs.aws.amazon.com/ses/latest/APIReference/API_SetIdentityHeadersInNotificationsEnabled.html
> Add SES.set_identity_headers_in_notifications_enabled/3

- lib/ex_aws/cloudformation.ex
- lib/ex_aws/utils.ex
- test/lib/ex_aws/utils_test.exs
Using `Kernel.apply` in the Cloudformation module look to have cleaned up a lot of boilerplate code for the transforms, but unfortunately also exposed many helper functions to the public interface that **should not be used directly**. This pull request fixes that issue by replacing apply with function patern_matching.  
Also added tests for build_indexed_params.
> Fix incorrectly public functions in Cloudformation module

- lib/ex_aws/s3.ex
Fixing the config type for presigned_url.
> Invalid typespec for `S3.presigned_url`

- lib/ex_aws/cloudformation.ex
- lib/ex_aws/utils.ex
- test/lib/ex_aws/cloudformation_test.exs
- test/lib/ex_aws/utils_test.exs
General cleanup of the cloudformation module, and changed to the relevant utils. Including 
- Additional documentation for cloudformation
- Better overall naming of cloudformation's new functions
- Renamed cloudformation's private `transform` functions to `format_param` 
- Refactored Utils.build_indexed_params to flatten_params. Now recursive, making for more concise usage. 
- Refactored `format_param` functions to use new Utils.flatten_params
- Added `Utils.maybe_format` macro. A very simple macro for calling private `format_param` functions if the param isn't null.
- Added `Utils.maybe_camelize` and `Utils.maybe_stringify` to reduce atom and string checking clutter
- Added `__using__` macro to `Utils` for basic `import + require`
> Cleanup of cloudformation, and related Utils functions. 

- lib/ex_aws/dynamo.ex
It appears streams for dynamo queries were never implemented even though there is a [method](https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/dynamo/lazy.ex#L31) for it. [`Dynamo.scan/2` implemented the stream builder](https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/dynamo.ex#L290), but [`Dynamo.query/2` did not](https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/dynamo.ex#L328).
> Add stream support for Dynamo.query/2

- lib/ex_aws/sts.ex
- lib/ex_aws/sts/parsers.ex
- test/lib/ex_aws/sts_test.exs
Some services don't allow cross-account permissions without using AssumeRole. 
While I was in there I added two other missing methods - DecodeAuthorizationMessage and GetSessionToken. 
This still leaves two missing methods:
AssumeRoleWithSAML
AssumeRoleWithWebIdentity
I can't see any use for WebIdentity in elixir, as it is designed for mobile app authentication. The SAML method would be very difficult to test, and they don't even provide sample request/response data on that doc. I'd rather err on the side of caution and not include them, but certainly could if that's preferred.
> add sts methods: assume role, decode_authorization_message, get_session_token

- lib/ex_aws/cloudformation.ex
- test/lib/ex_aws/cloudformation/integration_test.exs
- test/lib/ex_aws/cloudformation_test.exs
One Cloudformation integration test was failing due to using the `:status_filter` param instead of the updated  `:stack_status_filters`. This was changed because `:status_filter` doesn't match the AWS spec `StackStatusFilter`.  And doesn't match `ExAws.Cloudformation`'s own naming convention of pluralizing params that require lists. (for example `stack_status_filters: [...]`)
In addition to fixing the integration test, support for the old `:status_filter` param has been readded with a deprecated warning. This function should be removed in 1.2.
> Added (deprecated) support for :status_filter param

- lib/ex_aws/utils.ex
`use ExAws.Utils` expands to four partially applied Util functions with `:non_standard_keys` and `:format_type` automatically applied to every relevant Util function. This is very useful for removing some unnecessary, and hard to read code. 
Unforchenetly our implementation of `Utils.__using__` was adding public functions. We were foreseeing a possible use-case where having `Cloudformation.format` be public would be useful. But we neglected to think about the documentation. 
While there is no downside from an encapsulation standpoint, it clutters the documentation with functions that the end user doesn't need to know about. This pull request changes the functions to be private.
There are other ways of addressing the above-mentioned usecase that don't have this downside. So this is …
> Make `use ExAws.Utils` expanded functions private

- lib/ex_aws/lambda.ex
Given the type spec:
```
@doc "Invoke a lambda function"
@type invoke_opts :: [
{:invocation_type, :event | :request_response | :dry_run} |
{:log_type, :none | :tail} |
{:qualifier, String.t}
]
```
we should convert all the options values to the AWS expected format, ie:
- Event, RequestResponse, DryRun
- None, Tail
This is the error raised by the AWS Lambda subsystem:
```
iex(2)> ExAws.Lambda.invoke("echo", %{}, %{}, invocation_type: :dry_run) |> ExAws.request
{:error,
{:http_error, 400,
%{body: "{\"message\":\"1 validation error detected: Value 'dry_run' at 'invocationType' failed to satisfy constraint: Member must satisfy enum value set: [DryRun, RequestResponse, Event]\"}",
headers: [{"Content-Type", "application/json"},
{"Date", "Sun, 02 Jul 2017 11:28:05 GMT"},
{"x-amzn-ErrorType", …
```
> [bug fix] camelize values of Lambda.invoke() options :invocation_type and  :log_type

- README.md
- lib/ex_aws/utils.ex
Another very small pull request. But I think it's a good idea to be clear that EC2 and Cloudformation are not yet fully fleshed out and with parsers.
Readme now has
- `ExAws.Cloudformation (BETA)`
- `ExAws.EC2 (BETA)`
- `ExAws.ECS (COMING SOON)`
> Add (beta) tags to readme for cloudformation and EC2

- lib/ex_aws/sqs/parsers.ex
Gets rid of the following warning:
```
warning: variable "val" is unused
lib/ex_aws/sqs/parsers.ex:273
```
> Gets rid of unused variables warning.

- lib/ex_aws/instance_meta.ex
For example, if the EC2 instance has no IAM Role attached the response is "404 not found".
> Detect error in instance_meta HTTP GET request

- lib/ex_aws/lambda.ex
- lib/ex_aws/s3.ex
Some fixes to **spec for map()** type.
> the syntactic representation of map() is %{optional(any) => any}, not %{}. The notation %{} specifies the singleton type for the empty map.
PS: I see there is no dialyzer step in your travis build. Currently dialyzer reports about 19 warning. I think could be useful to fix those and add a dialyzer step in travis to find immediately grey spots in new code.
> fix @spec for map() type

- test/lib/ex_aws/sqs_test.exs
Hello!
I found the wrong name of an argument while using tests as a source of SQS query samples - `wait_timeout` but it should be `wait_time_seconds`.
Thank you for your work!
> Tests: SQS.receive_message wrong argument name

- lib/ex_aws/auth.ex
```
==> ex_aws
Compiling 61 files (.ex)
warning: String.rstrip/1 is deprecated, use String.trim_trailing/1
lib/ex_aws/auth.ex:137
warning: String.strip/1 is deprecated, use String.trim/1
lib/ex_aws/auth.ex:185
Generated ex_aws app
```
> Fixed Elixir 1.5 deprecation warnings

- lib/ex_aws/cloudformation.ex
The syntax error in the doc section prevents copy/paste execution. :)
> Fixing Syntax Error in CloudFormation Doc

- lib/ex_aws/auth.ex
- test/lib/ex_aws/s3_test.exs
AWS supports ? in key names however the way we were previously encoding
the URL to be signed caused these query params to be dropped.
For more info on what S3 supports in keys see:
http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-keys
> Add support for query params in S3 key names

- lib/ex_aws/s3.ex
- lib/ex_aws/s3/utils.ex
- test/lib/ex_aws/s3_test.exs
This PR fixes`S3.presigned_url/4` and friends so that they respect a port specified in the S3 config.
Fixes #363.
> Fix presigned URL port handling

- lib/ex_aws/config/auth_cache.ex
Currently, if refresh_in determines that the credentials should have already been refreshed, the auth_cache process crashes. While I believe that (functionally) the code after this change has the same effect, the error is no longer logged.
> Do not pass negative ms to send_after in AuthCache

- lib/ex_aws/instance_meta.ex
When building paths to retrieve instance metadata, you would end up with double slashes: http://169.254.169.254/latest/meta-data*//*iam/security-credentials/
AWS instance metadata doesn't seem to care about the double slash, but when using services like kube2iam in order to expose IAM profiles to Kubernetes pods, sometimes they do care and won't work.
After merging, can you release a new version? I depend on this and I don't want to be using deps from git.
> Fix double slash on instance metadata queries

- lib/ex_aws/ec2.ex
Follow to this document, the following error occurs: 
```elixir
iex(2)> ExAws.EC2.run_instances("ami-123456", 1, 1, [tag_specifications: [{"instance", [Name: "Test"]}]])
** (ArgumentError) argument error
:erlang.atom_to_binary("instance", :utf8)
(ex_aws) lib/ex_aws/ec2.ex:2758: anonymous fn/2 in ExAws.EC2.format_param/1
(elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
(ex_aws) lib/ex_aws/ec2.ex:2763: ExAws.EC2.format_param/1
(elixir) lib/enum.ex:988: Enum.flat_map_list/2
(elixir) lib/enum.ex:989: Enum.flat_map_list/2
(ex_aws) lib/ex_aws/ec2.ex:2624: ExAws.EC2.build_request/2
```
but, success when follow to modified typespec: 
```elixir
iex(2)> ExAws.EC2.run_instances("ami-123456", 1, 1, [tag_specifications: [{:instance, [Name: "Test"]}]])
%ExAws.Operation.Query{action: …
```
> Fix typespec of `tag_specification`

- lib/ex_aws/s3/download.ex
- lib/ex_aws/s3/upload.ex
- lib/ex_aws/sqs/parsers.ex
These extra commas results into error when compiled with Elixir 1.6
e.g.
```
== Compilation error in file lib/ex_aws/s3/download.ex ==
** (SyntaxError) lib/ex_aws/s3/download.ex:75: syntax error before: ')'
(elixir) lib/kernel/parallel_compiler.ex:160: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/1
```
```
== Compilation error in file lib/ex_aws/s3/upload.ex ==
** (SyntaxError) lib/ex_aws/s3/upload.ex:88: syntax error before: ')'
(elixir) lib/kernel/parallel_compiler.ex:160: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/1
```
```
== Compilation error in file lib/ex_aws/sqs/parsers.ex ==
** (SyntaxError) lib/ex_aws/sqs/parsers.ex:142: syntax error before: ')'
(elixir) lib/kernel/parallel_compiler.ex:160: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/1
```
> Fix errors to make it ready for Elixir 1.6

- README.md
- mix.exs
- mix.lock
When `:aws_instance_auth` & `:awscli` config are expired,  `ExAws.Config.AuthCache.get` is called for loading config at runtime. And every time called, some processes have generated and still alive through app running.
That is caused by `StringIO.open(config_string)` is used for reading string then return result without closing it (`StringIO.close(pid)`).
It is fixed and available in `configparser_ex` 2.0.1 version now.
[https://github.com/easco/configparser_ex/releases/tag/2.0.1](https://github.com/easco/configparser_ex/releases/tag/2.0.1)
> Fix: parsing config causes unused processes to accumulate

- README.md
When we used ex_aws on Kubernetes, with a proxy between the machine and AWS API, the default setup would not work as the requests to the instance meta [would only work if the response was 200](https://github.com/ex-aws/ex_aws/blob/master/lib/ex_aws/instance_meta.ex#L17). The proxy for us was doing a 301 or 302 redirect, so it'd fail.
Traced back the options being passed around to some defaults that don't have the `follow_redirect` flag set, realised we can overwrite those.
Hoping the explicit mention in the README helps the next person with this problem in the future. :)
/cc @zzeniou86
> Show an explicit example of changing hackney options

- CONTRIBUTING.md
Running mix test limited to the IAM permissions currently specified in the contributing document results in failures on Cloudformation integration tests.
This is a simple update to add the necessary permissions to the contributing document
> Update the CONTRIBUTING required policy document to include cloudformation permissions

- lib/ex_aws/config.ex
Hi, thank you for great product ex_aws.
In `ExAws.Config.build_base/2` region string is passed to `ExAws.Config.Defaults.get/2`, however this comes from `overrides` and falls back to "us-east-1". This behaviour ignores region configuration in `common_config` or `service_config`. leads to getting an error such as reported in #359
> Region of service and common config is ignored

- README.md
The `:sweet_xml` import is missing an arrow in the docs, which makes it an invalid config setting when copy/pasted. Fixing the typo.
> Fixing typo in import statement for README.md

- lib/ex_aws/auth.ex
- test/ex_aws/auth_test.exs
This is a prerequisite for https://github.com/ex-aws/ex_aws_rds/issues/2. I could not find official documentation for implementing this behavior (they push you to the CLI), but I analyzed the botocore implementation to determine this. 
https://github.com/boto/botocore/blob/develop/botocore/auth.py#L262
They use some request metadata to automatically determine if a nil body should return the EMPTY_SHA256_HASH vs "UNSIGNED_PAYLOAD", but that seems like a much more invasive change - I can simply pass an empty string for the body content and `ExAws.Auth.build_canonical_request/5` will handle it correctly.
> generate a presigned URL with body content

- lib/ex_aws/request.ex
Removes the `body` key matching in `ExAws.Request.request_and_retry/7`
Closes https://github.com/ex-aws/ex_aws/issues/525
> Fix ExAws.Request.request_and_retry/7 case clause error where the body key is missing

- README.md
- lib/mix/tasks/tail.ex
This pull request prefixes the kinesis.tail mix task with `aws` in order to establish a common prefix for mix tasks of `ex_aws`.
For further reference see #528
> Rename kinesis.tail mix task to aws.kinesis.tail

- README.md
This is to help users who are not in `us-east-1` have a hint on how to get up and running faster.
> Add a hint that you can set the region in `ExAws.request/2`

- lib/ex_aws/request.ex
Do not mutate URL so recursion works when the URL contains a space.  When retrying, the header was recomputed using a "modified" URL and was at the root of a `SignatureDoesNotMatch` error from S3.
> Fix SignatureDoesNotMatch error when retrying a request

- README.md
This is trivial, but it caught my eye when I opened the repo. Might as well be consistent with the style of the running code.
> Show consistent formatting in README code example

- mix.exs
The URL of the repo has changed as it's been moved to an organisation.
> Update links to GitHub repo

- lib/ex_aws/config/defaults.ex
Currently trying to do an operation with the `iot_data` service causes the following runtime error:
`(RuntimeError) iot_data not found in partition aws`
This properly maps `iot_data` to `data.iot`  in the endpoints file and overrides the service to use `iotdata`.
Followed the conventions for `dynamodb_streams` and `sagemaker_runtime`
> Properly set defaults for iot_data service

- lib/ex_aws/request.ex
Currently, ExAWS reports errors with `Logger.warn/2`, but we want to know what the request failed. So this PR adds request information if `config[:debug_requests]` enabled.
> Log error and details of the failed request

- lib/ex_aws.ex
- lib/ex_aws/behaviour.ex
I found [this discussion](https://github.com/ex-aws/ex_aws_s3/issues/27) in the s3 repo, but it looks like nothing ever came of it. I think it's pretty important to be able to Mox pretty much anything that one would do with s3 for testing. Thanks to how you've set up the library, it's such a small change to make that possible!
> Add a behaviour for the toplevel functions

- priv/endpoints.exs
Adds endpoints for the AWS Transcribe service based on [AWS Regions and Endpoints](https://docs.aws.amazon.com/general/latest/gr/rande.html#transcribe_region) page.
Works with [ex_aws_transcribe](https://hex.pm/packages/ex_aws_transcribe).
> AWS Transcribe endpoints

- README.md
- lib/ex_aws/operation.ex
I don't have much experience using the AWS HTTP API directly except for figuring out how to run an ECS task with this library, so I would appreciate a thorough review. The contributing guidelines about adding new service modules were quite helpful.
I found four different implementations of `ExAWS.Operation`: `JSON`, `Query`, `RestQuery`, and `S3`. The example of `JSON` is from my own app, the example of `Query` is from the contributing guidelines.
I didn't mention `S3` because there is a service module for S3.
I didnt' mention `RestQuery` because I do not know for which AWS service it could be used. In https://github.com/aws/aws-sdk-go/tree/master/models/apis (mentioned in the contributing guidelines), I only found protocols "query", "json", and "rest-json" - not "rest-query". If somebody …
> Describe direct usage

- lib/ex_aws/auth.ex
Addresses ex-aws/ex_aws_s3#36, see my comments on #540 for the rationale.
> Add an additional parameter to ExAws.Auth for specifying headers.

- lib/ex_aws/config/defaults.ex
I am working on lex runtime and models services for ex_aws. `models.lex` or `runtime.lex` is prefixed in url and `lex` is used in credential scope. It would nice to get it in the ex_aws.
Also, are we doing any new releases for changes like these? Looks like sagemaker change like this is not in the hex yet.
> add support for lex models and runtime on service overrides

- lib/ex_aws/credentials_ini.ex
I am having an issue with this method, that always return an empty Map even when I have a `.aws/config` file present.
Given the following file:
```
[profile test]
source_profile=credential_name
role_arn=arn:aws:iam:::role/
mfa_serial=arn:aws:iam::::/
```
`ExAws.CredentialsIni.security_credentials("test")` will always return `%{}` when using `String.to_existing_atom`
Changing it to `String.to_atom` fixes the problem and the output is now:
```elixir
%{
mfa_serial: "arn:aws:iam::::/",
role_arn: "arn:aws:iam:::role/",
source_profile: "credential_name"
}
```
> Change .to_existing_atom to .to_atom method for parse_ini_file

- lib/ex_aws/request/http_client.ex
The HttpClient example was misleading not only for me but I can see in the Issues another user, it led users of ExAws to believe 
that ExAws.Request.HttpClient.request/5 only took /4. Have also added
some extra description to help with the conforming of the Client.request
firing to give a bit more clarity.
> Update HttpClient example to follow @callback

- lib/ex_aws/operation/s3.ex
Hello ExAws devs,
for a project of ours we're working with a German cloud provider who offer S3 services. We ran into an issue with the `get_object/3` operation (likely all `get_*` operations, but we didn't test others) that responds with an `InvalidAccessKeyId` error, while `put_object/3` and friends are working fine. Retrieving objects using [s3cmd](https://s3tools.org/s3cmd) and even curl worked fine, though, so we suspected the problem to originate within ExAws.
After some debugging, we found out that ExAws is including `Content-Length: 0` in the request headers as well as the `Signed-Headers` in the AWS signature for all requests. Removing this header for empty `GET` requests fixes the issue.
While this is likely to be a quirky detail of whatever S3 implementation our hoster is …
> S3: Do not include content-length in GET headers.

- README.md
- lib/ex_aws/config.ex
- mix.exs
- test/ex_aws/config_test.exs
This PR enables the use of an envar `AWS_REGION` to externally control the region configurations of `ex_aws`  usage.  
The PR provides:
- a simple change to the code that determines the region
- two new tests to confirm that plain-text and system envar configurations both work as expected.
> enable system envar spec for region config

- priv/endpoints.exs
Add eu-central-1 region to the list of AWS translate endpoints in order to support the requests to AWS Translate API in this region.
> Add eu-c-1 region to list of Translate endpoints

- lib/ex_aws/auth.ex
- lib/ex_aws/auth/utils.ex
- lib/ex_aws/request.ex
- lib/ex_aws/request/url.ex
- lib/ex_aws/utils.ex
- test/ex_aws/auth_test.exs
- test/ex_aws/request/url_test.exs
- test/ex_aws/request_test.exs
I was getting errors when trying to download certain files with special characters from S3 such as `+` and `#`
The root issue is that URLs were being parsed and losing some information from the URL before signing and requesting the URL. For example, if an end-user uploads a file to S3 with this filename: 
`test hello+#3.txt`, it's not URL-encoded correctly and would fail a normal web request, saying either the key didn't exist, or a 403. We need that URL-encoded to `test%20hello%2B%233.txt`. 
When parsing the URL, we currently use Elixir's built-in URI functions:
```elixir
iex(1)> URI.parse("https://examplebucket.s3.amazonaws.com/test hello+#3.txt")
%URI{
authority: "examplebucket.s3.amazonaws.com",
fragment: "3.txt",
host: "examplebucket.s3.amazonaws.com",
path: "/test hello+",
port: …
```
> Fix URL encoding for S3 objects with special characters

- lib/ex_aws/credentials_ini.ex
The AWS CLI supports specifying a "credential process", which is a
command that can be run once or periodically to fetch credentials in a
specified JSON format.
https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#sourcing-credentials-from-external-processes
While this commit does not add support for actually running the command,
it does make it possible to run
ExAws.CredentialsIni.security_credentials("my_profile")
and get back `credential_process` as one of the configuration values in
the map, such as
%{
credential_process: "my_command -user me -role some_role",
region: "us-west-2"
}
> Parse the credential_process config value

- lib/ex_aws/config.ex
- lib/ex_aws/config/defaults.ex
- lib/ex_aws/request/url.ex
- test/ex_aws/request/url_test.exs
Very old s3 objects can have a leading forward slash and normalizing makes those objects inaccessible. Fixes https://github.com/ex-aws/ex_aws_s3/issues/58
> Allow turning off normalize_path

- mix.exs
With the release of Jason 1.2, having a dependecy on `~> 1.1.0` becomes
a problem. Example:
```
Failed to use "jason" because
[...]
ex_aws (version 2.1.2) requires ~> 1.1.0
```
This can be resolved by simply depending on `~> 1.1`.
> Relax Jason dependency version

- lib/ex_aws/config/auth_cache.ex
- test/ex_aws/auth/auth_cache_test.exs
In a high throughput application using the `awscli_auth_adapter` option we were seeing a small percent of errors that seem to correlate with the `AuthCache` refresh period:
`{:error, "Required key: :secret_access_key is nil in config!"}`
This can happen as the auth config loaded from the configuration file (that can be used for the adapter but is not the final credentials to be used for AWS requests - as it may not have the same permissions or can even be empty when using ENV vars) is temporarily stored in `:ets` that can be concurrently read.
The attached unit test was able to reproduce the issue and is currently passing with the proposed fix.
> High concurrency on ets can cause dirty cache to leak empty/wrong auth

- priv/endpoints.exs
This facilitates the creation of an `ex_aws_connect` library. Otherwise I'm finding that in spite of adding `config :ex_aws, :connect, ...` there will always be an exception from `ExAws.Config.Defaults.fetch_or/3`.
> Add connect to endpoint default configuration

- lib/ex_aws/auth.ex
- test/ex_aws/auth_test.exs
Specifies a list of unsignable headers that are not used for the signature in the authorisation header. This is required as the `X-Amzn-Trace-Id` header can be sent, but should not be used in the Signature in the request's `Authorization` header. This is confirmed by the [js-sdk](https://github.com/aws/aws-sdk-js/blob/master/lib/signers/v4.js#L191-L199).
I am not too convinced by having the `unsignable_headers` list specify both uppercase and lowercase formats. I did originally have another iteration over the headers after the current `Enum.map` where the keys would always be downcased, perhaps this is better? Happy to discuss/change this!
I am aware that not everyone will be using the unsignable headers such as the `X-Amzn-Trace-Id` and therefore have tried to make as small impact on …
> Unsignable request headers

- priv/endpoints.exs
Rekognition is already supported in ap-southeast-1 as per:
https://aws.amazon.com/about-aws/whats-new/2019/06/amazon-rekognition-available-four-additional-aws-regions/
> added ap-southeast-1 endpoint for rekognition

- lib/ex_aws/operation/s3.ex
As per type spec contract on `ExAws.Request.HttpClient` the `request` callback ask for `headers :: [{binary, binary}, ...]`:
```elixir
@type http_method :: :get | :post | :put | :delete
@callback request(
method :: http_method,
url :: binary,
req_body :: binary,
headers :: [{binary, binary}, ...],
http_opts :: term
) ::
{:ok, %{status_code: pos_integer, body: binary}}
| {:error, %{reason: any}}
```
in this case we have `{"content-length": 13}` where the value is an int.
NOTE: it works now with the default hackney client because it accepts and coverts this type
https://github.com/benoitc/hackney/blob/2f55c0d37f9d5942b976272a1df5adecca4edc61/src/hackney_bstr.erl#L30
I've noticed this because I'm using a different HTTP client and I expected to receive a `[{binary, binary}]`
> HTTP header value should be a String (binary)

- lib/ex_aws/auth.ex
Keyword.keys() cannot be used for non-keyword lists from [Elixir 1.11](https://github.com/elixir-lang/elixir/blob/v1.11/CHANGELOG.md#elixir-1); it was used here with a `[{String.t, String.t}]` instead. This fix concatenates signed headers using dedicated function.
> Elixir 1.11 compatibility

- lib/ex_aws/config/defaults.ex
- priv/endpoints.exs
Amazon Timestream is available in US East (N. Virginia), US East (Ohio), US West (Oregon), and EU (Ireland), with availability in additional regions in the coming months.
Amazon Timestream is split into two services 
- [Amazon Timestream Write](https://github.com/aws/aws-sdk-go/blob/master/models/apis/timestream-write/2018-11-01/api-2.json)
- [Amazon Timestream Query](https://github.com/aws/aws-sdk-go/blob/master/models/apis/timestream-query/2018-11-01/api-2.json)
This PR adds valid endpoints and valid configurations
Example:
```elixir
%ExAws.Operation.JSON{
http_method: :post,
service: :ingest_timestream,
data: %{},
headers: [
{"x-amz-target", "Timestream_20181101.DescribeEndpoints"},
{"content-type", "application/x-amz-json-1.0"}
]
} |> ExAws.request(region: "us-west-2")
```
Response: …
> Timestream AWS service - add endpoints

- lib/ex_aws.ex
- mix.exs
- test/ex_aws/auth_test.exs
This addresses the the following compiler warning when using Elixir 1.11:
```
warning: Supervisor.Spec.worker/2 is deprecated. Use the new child specifications outlined in the Supervisor module instead
lib/ex_aws.ex:93: ExAws.start/2
```
Also, fixed the `unused variables` warnings when running `mix test` as well. The min version was bumped to `1.5` since that was when the new Supervisor changes was added in.
> Fix Elixir 1.11 compiler warning

- priv/endpoints.exs
Following previous https://github.com/ex-aws/ex_aws/pull/717 🤦‍♀️ 
`(RuntimeError) firehose not supported in region ca-central-1 for partition aws`
> Support firehose in region ca-central-1

- .travis.yml
- lib/ex_aws.ex
- mix.exs
List of changes:
- Add maintainer email to Travis CI notification
- Add changelog link to hex module info page
- Set readme as HTML doc default page which fix the badges issue. See screenshot.
> Extra HTML doc changes and fixes

- priv/endpoints.exs
SES is supported in `us-east-2`. I've tested this fork in AWS and received an email from my domain.
> Add us-east-2 as allowable SES email endpoint

- lib/ex_aws/auth/utils.ex
:crypto.hmac/{3,4} is deprecated and will be removed in Erlang/OTP 24.
:crypto.mac/4 is used instead. It is available since Erlang/OTP 22.1, so some availability checks must be performed.
> Use :crypto.mac/4 instead of :crypto.hmac/3

- config/test.exs
After the Nth failure to remember to setup the env vars expected for the API keys while testing, I added fake credentials to the test configuration. One less thing to remember, get wrong, and/or risk accessing actual data with real secrets floating in the ENV, this makes testing a bit easier.
> Provide fake secrets for testing purposes

- config/test.exs
- lib/ex_aws/operation/s3.ex
- test/ex_aws/operation/s3_test.exs
This is a proposed alternative approach to #726 
This is done in a backwards compatible manner to preserve existing configurations. In the next major release, consider switching the default to virtual host style as that is the current recommendation from S3 API providers.
Test coverage and typespecs for the functions were added, and I have also tested in a real-world application that uses virtual host style hostnames to differentiate buckets.
> Support virtual host style buckets

- lib/ex_aws/auth.ex
This is a possible fix for #733 in which the parameters passed as part of the URL as included with the rest of the URL params, avoiding broken urls with things like "?foo=bar?X-Amz-Signature.
I am not 100% sure if this is the correct fix, but it looks so according to the documentation. Missing test suites for this code do not help, and should really be added in order to determine correctness. The best I can say is that the test suite that exists works, that  a correct test suite in `ex_aws_s3` now passes, and a local app I have written which uses `ex_aws_s3` still works as well though it is not hitting all of the affect code paths. 
Therefore, I consider this a moderately risky merge, though it does address what looks to be an obvious error?
> Attempt to fix presigned urls with query strings

- lib/ex_aws/credentials_ini.ex
- test/ex_aws/config_test.exs
`aws-cli` supports choosing the profile from the AWS_PROFILE variable. With this change the profile will be resolved on runtime so the same build can be executed with any local profile.
Old config (hardcoded profile name):
```ex
config :ex_aws,
access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, {:awscli, "default", 30}, :instance_role]
```
dynamic profile selection (from env):
```ex
config :ex_aws,
access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, {:awscli, :system, 30}, :instance_role]
```
> Support reading the profile from env variable

- lib/ex_aws.ex
- lib/ex_aws/config/auth_cache.ex
- lib/ex_aws/utils.ex
- test/ex_aws/utils_test.exs
This PR attempts to address a few different issues highlighted as a result of PR #625 including:
* enforce the singleton status of the AuthCache module
* always check returned auth and re-fetch if non-existent or expired
* only perform a scheduled refetch if the cached auth is close to expiry
* replace the hand-rolled time offset code with NaiveDateTime
It is separated into 3 different commits so each may be reviewed and easily only take parts. If this approach is acceptable and works as desired, a similar change should be made for the `:refresh_awscli_config` paths as well. 
I have very limited ability to test this thoroughly, so testing by those following PR #625 would be great welcomed.
> Refactor auth cache refreshing

- priv/endpoints.exs
Athena is supported in EU-WEST-2 (London Region)
> Added eu-west-2 as an athena endpoint

- config/test.exs
- lib/ex_aws/instance_meta.ex
- test/ex_aws/instance_meta_test.exs
It is possible to configure the HTTP client on per-service basis. However this is not possible when fetching AWS metadata (specifically, fetching IAM credentials from the EC2 instance role). This risks metadata requests competing for connections with other requests and can lead to starvation in extreme cases.
This PR is an attempt to enable providing configuration separately for metadata requests, like so:
```
config :ex_aws, :metadata,
http_opts: [
pool: :ex_aws_metadata
]
```
More context is here: https://github.com/ex-aws/ex_aws/issues/598
> Allow separate configuration of http_opts used for AWS metadata

- priv/endpoints.exs
What does this do?
-------------------
I was looking to send emails from my app and then I was running into the `<service> not supported in region <region> for partition aws` error as per this issue: https://github.com/ex-aws/ex_aws/issues/682
So this adds `us-west-1` as an option for sending emails.
Technical Considerations
-------------------------
- I *think* that `email` is the correct key in the configuration mapping (I was originally looking for `ses`).
- This is where I looked to see if `us-west-1` *should* be supported: https://docs.aws.amazon.com/general/latest/gr/ses.html
Happy to look in other places as well if that is not the best spot!
> Add us-west-1 to list of supported ses services.

- lib/ex_aws/config.ex
- lib/ex_aws/config/auth_cache.ex
- lib/ex_aws/credentials_ini/file.ex
- lib/ex_aws/credentials_ini/provider.ex
- test/ex_aws/config_test.exs
- test/ex_aws/credentials_ini/file_test.exs
- test/test_helper.exs
In order to make `ex_aws` fully production-ready, we need to take into account the containerized applications that run, for example, over Kubernetes or Nomad. A typical configuration of secrets for this kind of application is by injection using environment variables. It is very common to restrict write permissions on the file system to avoid security problems also.
The aforementioned facts enter in conflict with the design of the STS module which resides on a file system file in order to assume a role for example.
I bring a proposal with implementation where I try to allow the injection of auth credentials by configuration, allowing the user to decide if using a file in the file system or not using the current design.
I also created the concept of `CredentialsIni.Provider` as I considered …
> Allow STS credentials to be injected by configuration

- config/test.exs
- lib/ex_aws/instance_meta.ex
- test/ex_aws/instance_meta_test.exs
The change in 01fad68 introduced a new required parameter
> make :http_opts for AWS metadata requests optional

- lib/ex_aws/config/auth_cache.ex
The current auth refresh time calculation
```elixir
max(expires_in_ms, expires_in_ms - @refresh_lead_time)
```
will always result in the auth being refreshed at the moment it expires rather than `lead_time` before expiration since `@refresh_lead_time` is positive. I believe the intention of this function is to return the ms to `lead_time`, unless it's negative and otherwise return 0 - meaning refresh now.
> Fix lead time in auth next refresh calculation

- lib/ex_aws/config/defaults.ex
- priv/endpoints.exs
This adds support for the Cape Town region. 
The region has not been added to some, but not all the services that are available in Cape Town. 
The endpoints.exs file seems to have a striking resemblance to this file, 
https://github.com/boto/botocore/blob/master/botocore/data/endpoints.json, as mentioned in this post: 
https://www.transposit.com/blog/2019.10.21-aws-regions-api/
Can I update the contents of priv/endpoints.exs with the contents of the endpoints.json file from Boto?
> Support for af-south-1

- priv/endpoints.exs
Was getting an error when trying to do operations of files in S3 inside the South Africa (af-south-1) region:
`** (RuntimeError) s3 not supported in region af-south-1 for partition aws`
Noticed the region wasn't added to the endpoints file for S3.
> add "af-south-1" to S3 region in EX_AWS

- lib/ex_aws.ex
- lib/ex_aws/config.ex
- lib/ex_aws/request.ex
- mix.exs
- test/ex_aws/ex_aws_test.exs
- test/ex_aws/request_test.exs
- test/telemetry_helper.exs
- test/test_helper.exs
As mentioned [here](https://github.com/ex-aws/ex_aws/issues/661).
> It would allow users of this library to capture important metrics and send them to their monitoring solution. This way, we save everyone the time to instrument their own usage of this library.
> Add telemetry events to all requests

- README.md
The latest version of `ex_aws` requires `configparser_ex` 4.0
Currently, following the readme results in this error message:
```
Failed to use "configparser_ex" because
ex_aws (version 2.2.3) requires ~> 4.0
mix.exs specifies ~> 2.0
```
> Bump readme configparser_ex version

- lib/ex_aws/auth.ex
When executing some profiles on services that uses ex_aws, for low CPU resource services, on of the main performance issues is the way this code is replacing the leading duplicate spaces.
To avoid this type of performance issue, this PR aims to replace the pattern matching code style by a regex match/replace mechanism.
> Replaces pattern-matching by regex to remove leading duplicate spaces on auth request headers

- mix.exs
Also I there's a license in `mix.exs` stated, I think it's better to also copy the LICENSE file into hexpm for better automatic license detection
> LICENSE file into hexpm

- CONTRIBUTING.md
- mix.exs
Turns out telemetry 0.4.0 doesn't include the `span` function.
Also add a comment about formatting contributions.
Resolves #794
> Tighten telemetry requirement

- lib/ex_aws/request.ex
- test/ex_aws/request_test.exs
After https://github.com/ex-aws/ex_aws/commit/ed5d8ce628cf06951fb89e2a49a0c26c57af861d# a breaking change was introduced. 
Before this, exceptions like DataAlreadyAcceptedException and InvalidSequenceTokenException produced errors that contained the expected sequence token and it could be directly used from the error map itself. Currently, errors are of the format `{:error, {type, message}}`, with the message containing the expected sequence token. To avoid parsing that error message, we can provide that token directly, like `{:error, {type, message, token}}` for the types of errors that contain this token.
I've also looked at the possibility of just having `{:error, reason}` where reason is the whole map returned by aws, containing the error type, message, and any other data like the …
> Return expected sequence token as part of error result

- lib/ex_aws/config.ex
Here's a simple config setup:
```elixir
config :ex_aws,
region: "us-east-1",
access_key_id: {:awscli, "default", 30},
secret_access_key: {:awscli, "default", 30}
```
```toml
[default]
region = "us-west-2"
```
I would expect `ExAws.Config.new(:s3)` to return a config where `region` is `"us-east-1"`, but it incorrectly returns `region: "us-west-2"` (all values configured in `~/.aws/{config, credentials}` take precedence over any other configured values, even if their keys aren't specified).
This PR modifies `ExAws.Config.retrieve_runtime_config/1` to only set the requested key(s), instead of merging in all available values.
Resolves #521.
> fix: prevent unrelated `awscli` config from leaking

- README.md
It claims the default JSON codec to be Poison.
It was changed into Jason in commit https://github.com/ex-aws/ex_aws/commit/efd3b660f2471ddbf6dc87e7269745a41500456c
2 years ago.
> Fix README codec section

- lib/ex_aws/config.ex
This reverts commit b6dd414bdd0c30ff54627ca399622fc10a1ad5f3.
Reverts #796.
Resolves #814.
> Revert "prevent unrelated awscli config from leaking"

- lib/ex_aws/operation/rest_query.ex
This change allows HTTP headers to be passed in. This was originally questioned when it was merged in here: https://github.com/ex-aws/ex_aws/pull/286#discussion_r90781530 but wasn't necessary for the use case at the time. However, attempting to use this with Cloudfront (and presumably any other service that utilizes ETag) makes this necessary.
This should add Headers if present, otherwise, leave them as an empty array. So, there should be no functional impact for existing users of this method.
> Pass Headers to Request

- lib/ex_aws/config/defaults.ex
- priv/endpoints.exs
To allow ex_aws to be used with the Amazon Augmented AI API (endpoint
`a2i-runtime.sagemaker.REGION.amazonaws.com`) a new service map override
has been added named `:sagemaker_runtime_a2i` to reflect the existing
`:sagemaker_runtime`
https://docs.aws.amazon.com/augmented-ai/2019-11-07/APIReference/API_StartHumanLoop.html
Example:
```
operation =
%ExAws.Operation.JSON{
http_method: :get,
path: "/human-loops",
service: :sagemaker_runtime_a2i
}
ExAws.request(operation)
```
> Add config for sagemaker_runtime_a2i

- priv/endpoints.exs
Noticed we were getting some errors for `rekognition not supported in region for partition aws`. Although, the specified region was supported according to the AWS documentation.
I've added the new supported endpoints: ap-south-1, ap-northeast-2, ca-central-1, eu-central-1, and us-west-1 for Rekognition following Amazons documentation: https://docs.aws.amazon.com/general/latest/gr/rekognition.html
> Adding new supported endpoints for Rekognition

- lib/ex_aws/config.ex
- test/ex_aws/config_test.exs
Passing Headers, such as `If-Match`, was previously causing issues. This is because the following code was executing when passing an array of header values:
```elixir
def retrieve_runtime_value(values, config) when is_list(values) do
values
|> Stream.map(&retrieve_runtime_value(&1, config))
|> Enum.find(& &1)
end
```
which destructured the data from `[{ "header-name", "header-value"}]` to `{ "header-name", "header-value"}` (note that it is no longer a list containing a tuple, but rather simply a tuple.
This caused issues later when trying to build up the headers to send in the request. Abbreviated for simplicity, we had:
```elixir
headers = { "some-key", "some-value" }
headers = [ defaultHeaders | headers ]
```
Because `headers` was no longer a `List`, the `headers` variable now contains …
> Support passing headers

- lib/ex_aws/request/url.ex
Found on Elixir 1.13, the compiler warning about usage of `?\ `. Fix
by using `?\s` instead.
> Use '?\s' instead of '?\ '

- lib/ex_aws/config/defaults.ex
As part of PR https://github.com/ex-aws/ex_aws/pull/845 we added the support for endpoints in me-south-1.
But it does not work unless the me-south-1 region is added to the default config to reference to the AWS partition.
So new region needs to be first tied to a partition by making the changing in the below file and then the endpoints.exs file is referenced by the code 
fixes #844 
@bernardd pls merge and give us a tag to reference. Thanks
> adding me to "aws" partition

- priv/endpoints.exs
Athena is now available in AWS in ca-central-1
https://aws.amazon.com/about-aws/whats-new/2019/03/athena_canada_central/
> Add Athena Support in ca-central-1

- lib/ex_aws/config/defaults.ex
- priv/endpoints.exs
Enables the usage of [AWS Location Service](https://docs.aws.amazon.com/location/latest/developerguide/what-is.html) for the relevant regions.
This includes the maps, places, geofencing, tracking, and routes services, for [nine supported regions](https://docs.aws.amazon.com/location/latest/developerguide/location-regions.html).
> Add Location service to "aws" partition

- lib/ex_aws/auth.ex
- lib/ex_aws/config.ex
- lib/ex_aws/credentials_ini/file.ex
- priv/endpoints.exs
- test/ex_aws/config_test.exs
- test/ex_aws/credentials_ini/file_test.exs
Work to resolve https://github.com/ex-aws/ex_aws/issues/843 based on the fork from @joeybaer. Huge thank you to both Joey and @patrickcsullivan for help and feedback on the PR!
Adds support in ExAws.CredentialsIni.File to pull the credentials expected throughout ex_aws from the temporary credentials provided by aws sso login stored in .aws/sso/cache/. This way users (like me) don't have to run a script prior to running elixir to generate the credentials and can instead just rely on the sso config like the aws cli does.
Sorry for a bit of spam creating this, didn't anticipate it would show up in the issue itself whenever I added a link to the issue from a PR description
> Add support for AWS SSO credentials

- lib/ex_aws/instance_meta_token_provider.ex
Some AWS services built on top of ECS such as codebuild and fargate will provide `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` env variable, that should be used with a different host to access the task credentials token, but the new `InstanceMetaTokenProvider` was ignoring this. If that env variable is present, it will build the token URL using it instead.
Fixes #869
> Support container task role credentials in token provider

- lib/ex_aws/config.ex
This PR updates the return type in spec for [`Config.new/2`](https://github.com/ex-aws/ex_aws/blob/c8015be9d89d9da2775b829b86ee4c6496877978/lib/ex_aws/config.ex#L39). Currently, the spec says that the return is specifically an empty map `%{}`, whereas I believe it should be the overall type `map()`.
For posterity's sake, I discovered this error when I tried to call [`S3.presigned_post/4`](https://github.com/ex-aws/ex_aws_s3/blob/6b375da2a1912d16f80e88860cbc9c74989588a9/lib/ex_aws/s3.ex#L1285) like so:
```
ExAws.Config.new(:s3)
|> ExAws.S3.presigned_post("bucket", "key")
```
which threw the following Dialyzer warning:
```
The call 'Elixir.ExAws.S3':presigned_post
(#{},
<<...>>,
<<...>>) will never return since it differs in the 1st argument from the success typing arguments: …
```
> Update spec for `Config.new/2` function

- lib/ex_aws/instance_meta_token_provider.ex
`InstanceMetaTokenProvider.request_token/1` currently uses an integer header value (`@metadata_token_ttl_seconds`), which breaks the contract for the `request` callback on `ExAws.Request.HttpClient`.
Similar to ex-aws/ex_aws#710
> Convert IMDSv2 header value to string

- lib/ex_aws/request/url.ex
- test/ex_aws/request/url_test.exs
Sometimes a URL may not specify a path to AWS, which in turn can cause an issue while a signature is being created for that URL.
**Current Behaviour:**
The following flow is executed when populating the headers
headers -> auth_headers -> signature -> get_path 
In get_path's current implementation, if the path is empty, it will return a nil value (which causes a matching error further on)
For example:
**Expected Behaviour:**
This PR adds a small change that allows for empty paths to be sent and the signature still being created for the specified URL. Instead of returning a nil value, get_path would return "/" upon discovering an empty path
**Note**:
Following the contribution guide here https://github.com/ex-aws/ex_aws/blob/bdc758048042e5db86179c843fdbbd9cbd2bbd4e/CONTRIBUTING.md
I tested …
> Handling empty paths sent to AWS

- priv/endpoints.exs
We are using `us-east-2` to manage our medialive channels but `us-east-2` still not supported in ExAws. 
The specified region is supported according to the AWS documentation.
I want to add all missing supported endpoints for medialive according to Amazons documentation:
https://docs.aws.amazon.com/general/latest/gr/medialive_region.html
> add more supported endpoints for medialive

- priv/endpoints.exs
I face this issue today:
```
s3 not supported in region ap-southeast-3 for partition aws
```
I propose the changes to add `ap-southeast-3`.
> Add ap-southeast-3 to s3 region

- lib/ex_aws/credentials_ini/file.ex
`profile_from_config` uses incorrect profile when `:system` is being used e.g. (`{:awscli, :system, timeout}`).
It'll use `profile default` instead of just `default` if the AWS_PROFILE env var is unset. This PR fixes it
> Use default profile when AWS_PROFILE is undefined

- priv/endpoints.exs
Hello and sorry for the impromptu request
We were testing a service for a couple of days and as we are using `elasticmq` locally we didn't run into this. However, as we deployed to our development environment we ran into this:
```
** (RuntimeError) sqs not supported in region me-south-1 for partition aws
(ex_aws 2.3.3) lib/ex_aws/config/defaults.ex:175: ExAws.Config.Defaults.fetch_or/3
(ex_aws 2.3.3) lib/ex_aws/config/defaults.ex:158: ExAws.Config.Defaults.do_host/3
(ex_aws 2.3.3) lib/ex_aws/config/defaults.ex:89: ExAws.Config.Defaults.get/2
(ex_aws 2.3.3) lib/ex_aws/config.ex:70: ExAws.Config.build_base/2
(ex_aws 2.3.3) lib/ex_aws/config.ex:43: ExAws.Config.new/2
(ex_aws 2.3.3) lib/ex_aws.ex:73: ExAws.request/2
```
So, I'm proposing adding the `me-south-1` region to the sqs endpoints …
> Add me-south-1 to sqs endpoints

- priv/endpoints.exs
This commit authenticates Amazon Cognito users requesting access from Canada(Central) region.
> Add ca-central-1 region to cognito-idp service

- test/ex_aws/instance_meta_test.exs
Resolve below warning:
warning: variable "opts" is unused (if the variable is not meant to
be used, prefix it with an underscore)
> Fix unused opts variables in tests

- priv/endpoints.exs
Problem
---------
I came across with the following error when I had tried to run `AWS Rekognition` for an image stored in S3 in London region (eu-west-2):
Fix
---
This PR adds missing `eu-west-2` region for Rekognition in 'priv/endpoints.exs file.
All service endpoints availables can be read in [Amazon Rekognition endpoints and quotas](https://docs.aws.amazon.com/general/latest/gr/rekognition.html) page.
> Adds missing region for Rekognition in priv/endpoints.exs

- lib/ex_aws/credentials_ini/file.ex
Closes #664.
I've been testing it locally for a couple weeks, since I now use 1Password to store my AWS credentials.
I did my best to add clear error messages 🙂!
Here's the relevant AWS documentation : https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html
> Add support for credentials_process

- priv/endpoints.exs
Added region `eu-west-2` to SageMaker endpoints so we can make use of [ex_aws_sagemaker_runtime](https://github.com/dideler/ex_aws_sagemaker_runtime) in this region.
> Add eu-west-2 to sagemaker endpoints

- lib/ex_aws/request/http_client.ex
Thank you for all your hard work! Below is a slight docs improvement.
A current example of custom `ExAws.Request.HttpClient` behaviour implementation always packs the response in `{:ok, result}` tuple, which only works for happy path and breaks if the underlying client returns an error.
The proposed example correctly packs errors in the error tuple that ExAws.Request.request_and_retry/7 function is expecting.
> Fix happy path-only http client doc

- priv/endpoints.exs
Firehose's eu-west-2 endpoint is not listed as active in the endpoints config. Therefore you get the error:
```
** (RuntimeError) firehose not supported in region eu-west-2 for partition aws
```
Checking the endpoints available for firehose, `eu-west-2` is listed as an active endpoint:
https://docs.aws.amazon.com/general/latest/gr/fh.html
> Add eu-west-2 to firehose endpoints

- lib/ex_aws/request.ex
- test/ex_aws/ex_aws_test.exs
Improve telemetry events with name of the `operation`, the new events will look like:
```elixir
%{
attempt: 1,
options: [],
result: :ok,
service: :secretsmanager,
operation: "secretsmanager.GetSecretValue"
telemetry_span_context: #Reference<0.3450093779.1724645383.45512>
}
```
> Add operation name to telemetry metadata closes #930

- lib/ex_aws/config.ex
When ExAws streams an operation, it calculates a config map once, then passes that config as "overrides" for each request during the stream. This means that auth creds are resolved _once_ and used for the entire duration of the stream. If you have a stream that takes longer than 6 hours on an EC2 instance, you'll eventually get "token expired" errors.
This PR detects refreshable creds in a config map, and uses `ExAws.Config.AuthCache` to resolve the creds on every request, even if an exist config map is passed as overrides.
This fix is completely transparent to downstream stream builders.
Fixes #824
I tested locally by printing to stdout, but I have no idea how to unit test it. I'm currently testing in production to see if it's ultimately effective.
Currently two types of configuration …
> Force refresh of config auth

- lib/ex_aws/request.ex
- test/ex_aws/ex_aws_test.exs
I'm working on a library to adapt ExAws's telemetry into [OpenTelemetry](https://opentelemetry.io/) data. OpenTelemetry actually has a set of recommendations for which data to include here: [Semantic conventions for AWS SDK](https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/instrumentation/aws-sdk/). If ExAws can include the request and response bodies in its telemetry, the adapter library can include all the data that OpenTelemetry requests.
The PR for that adapter library is here: <https://github.com/open-telemetry/opentelemetry-erlang-contrib/pull/152>.
> Add request and response to telemetry

- priv/endpoints.exs
Just supporting [IVS as authorized](https://docs.aws.amazon.com/ivs/latest/APIReference/API_CreateChannel.html) AWS service.
> Add support for IVS endpoints

- priv/endpoints.exs
Add `me-south-1` to the list of SNS endpoints so ex_aws won't error when connecting to valid sns endpoints.
[x] Run `mix format` using a recent version of Elixir
[x] Run `mix dialyzer` to make sure the typing is correct
[x] Run `mix test` to ensure no tests have broken (also please make sure you've added tests for your particular change, where appropriate).
I couldn't find tests that check this particular use case. I would be more than happy to add any if required.
> Add `me-south-1` to SNS endpoints

- priv/endpoints.exs
Adding support to [EventBridge Scheduler](https://docs.aws.amazon.com/scheduler/latest/APIReference/Welcome.html) as an AWS service.
> Add support for EventBridge Scheduler endpoints

- priv/endpoints.exs
Adds SQS endpoint for eu-central-2 Europe (Zurich)
> Add eu-central-2 to SQS endpoints

- priv/endpoints.exs
Adding the eu-south-1 (Milan) region to the list of endpoints.
> Add eu-south-1 to SQS endpoints

- lib/ex_aws/credentials_ini/file.ex
- lib/ex_aws/instance_meta.ex
- lib/ex_aws/instance_meta_token_provider.ex
- lib/ex_aws/request.ex
Thanks for the previous work to support Req in #976. Unfortunately it didn't _quite_ go far enough. There are a few more places that `.request` is called on the `http_client`, and they all need to have their responses transformed in case it's a Req response.
> Ensure that response is transformed with all requests

- lib/ex_aws/request/http_client.ex
There was a recent change to replace the `HTTPotion` example with `Req`, but one reference to `HTTPotion` was accidentally left in.
I changed that reference, but I also clarified the docs a tiny bit.
Thanks for the library!
> Improve docs regarding Req

- lib/ex_aws/config/defaults.ex
- priv/endpoints.exs
On _main_
`ExAws.Config.Defaults.host("sts", "us-east-1-fips")` would return `nil`.
With this PR, it returns
`"sts-fips.us-east-1.amazonaws.com"`
Plus,
Some endpoints are added.
> Add some fips endpoints. Perhaps a fix for the partition regex.

- lib/ex_aws/request.ex
- test/ex_aws/request_test.exs
Fixes https://github.com/ex-aws/ex_aws/issues/1005 by updating `request.ex` to also handle errors in the form of `[reason: reason]` in addition to `%{reason: reason}`.
[x] Run `mix format` using a recent version of Elixir
[x] Run `mix dialyzer` to make sure the typing is correct
[x] Run `mix test` to ensure no tests have broken (also please make sure you've added tests for your particular change, where appropriate).
> Update request logic to handle error reasons in keyword lists

- priv/endpoints.exs
I am building a ex_aws_incidents lib and those two endpoints are required.
Here are they in the aws-sdk-go: [ssm-incidents](https://github.com/aws/aws-sdk-go/blob/main/models/apis/ssm-incidents/2018-05-10/api-2.json) & [ssm-contacts](https://github.com/aws/aws-sdk-go/blob/main/models/apis/ssm-contacts/2021-05-03/api-2.json)
> Adds the ssm-incidents and ssm-contacts to the endpoints.exs

- lib/ex_aws/config/defaults.ex
- priv/endpoints.exs
This allows `ExAws.Config.new(:personalize)` to run without throwing an error.
> Add support for Personalize

- priv/endpoints.exs
Original:
iex(:)> ExAws.Config.Defaults.host("kms", "us-gov-east-1")
`"kms.us-gov-east-1.amazonaws.com"`
This commit brings:
iex(:)> ExAws.Config.Defaults.host("kms", "us-east-1-fips")
`"kms-fips.us-east-1.amazonaws.com"`
Docs:
https://aws.amazon.com/compliance/fips/
> Fix us-gov-east-1 kms endpoint.

- priv/endpoints.exs
Govcloud uses FIPS endpoint. The URL references are here according to AWS docs:
https://aws.amazon.com/compliance/fips/
> Fix s3 gov-us-east-1 and gov-us-west-1 URLs.

- lib/ex_aws/request/http_client.ex
This updates the Req example in the `ExAws.Request.HttpClient` documentation.
- Set `decode_body: false` to prevent Req from decoding JSON responses on its own (behaviour expects binary body).
- Rename `status` to `status_code` in response to conform to behaviour. I know ex_aws was updated to map the response on its own in the main branch, but the behaviour still prescribes a `status_code` field.
- Wrapped error into reason map as prescribed by behaviour.
- Added missing `@impl`.
- Added `moduledoc` to example for easier copy-and-paste into projects that enforce module docs with linter rules.
- Updated headers to avoid duplicate links in the sidebar.
> update Req HttpClient example

- priv/endpoints.exs
`me-south-1` is supported in the `aws` partition as can be seen here: https://docs.aws.amazon.com/general/latest/gr/s3.html
* Run `mix format` using a recent version of Elixir (check)
* Run `mix dialyzer` to make sure the typing is correct (check)
* Run `mix test` to ensure no tests have broken (also please make sure you've added tests for your particular change, where appropriate). (check)
> Add `me-south-1` to s3 endpoints

- priv/endpoints.exs
Hello! I am working with the Bedrock AWS service and would like to add this module to your project. I need the addition of the relevant endpoints (provided in this PR). For now I include all the supported regions with the exception of `fips` which I need to investigate - I see it requires different signing and I have not tested it :- https://docs.aws.amazon.com/general/latest/gr/bedrock.html#bedrock_region
I have implemented list, get and invoke models including streaming. I have not yet implemented agents or custom models - I want to start with the basics. 
I will publish the repo in the new year. Here is an example:
```elixir 
prompt = ~s[
Please write me a polite excited memo in the style of a GitHub pull request.
The project name is ExAws. The feature is adding AI capabilities."
] …
```
> Bedrock endpoints

- lib/ex_aws/request/http_client.ex
This builds on work in #1015 adding a bit of code to adjust the header format to the expected list of 2-element tuples.
Req 0.4+ changed the headers format to be a map where the key is a string and the value is a list of strings, e.g.:
```elixir
%{
"content-length" => ["12345"]
}
```
This req change makes the current example fail whenever you try to perform a streaming operation because the code in `ExAws.S3.Download` assumes a single value:
```elixir
defp get_file_size(bucket, path, config) do
%{headers: headers} = ExAws.S3.head_object(bucket, path) |> ExAws.request!(config)
headers
|> Enum.find(fn {k, _} -> String.downcase(k) == "content-length" end)
|> elem(1)
|> String.to_integer() # <- fails here because it gets a list
end
```
With the proposed change, the example implementation …
> Fix Req example HttpClient implementation for Req 0.4+

- lib/ex_aws/operation/s3.ex
👋 
This PR makes iodata ops possible in ExAws.S3.
> allow iodata body in s3 requests

- README.md
This PR adds example docker command to run DynamoDB locally. Saves contributors a click.
> document how to run DynamoDB locally

- lib/ex_aws/credentials_ini/file.ex
- test/ex_aws/credentials_ini/file_test.exs
This makes sso_session in ~/.aws/config work properly. See issue #951
It simply merges in the config entries from the specified sso-session section. It also changes the cache_key used from sso_start_url to the sso_session name when sso_session is specified.
> sso_session support in .aws/config

- lib/ex_aws/request/req.ex
- mix.exs
When communicating with storage backends over a local socket (using sendfile, responses are not limited to small chunks), hackney does not reliably handle responses above about 64MiB - see https://github.com/benoitc/hackney/issues/729
This adds a Req backend. Req is widely used and does not have such a limitation.
> Add Req request backend

- lib/ex_aws/operation/s3.ex
```elixir
defp put_content_length_header(headers, "", :head), do: headers
```
This extra function clause in `lib/ex_aws/operation/s3.ex` prevents the `content-length` header from being added to the headers of a `HEAD` request with an empty body (in which case the body of the request is an empty string and the value of that header would be "0"). 
This is compliant with [Amazon's specification of the HeadObject API endpoint](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html#API_HeadObject_RequestParameters), as it doesn't specify the `content-length` header as part of the URI Request Parameters.
As an added benefit, this makes ExAws and ExAws.S3 work with [Garage](https://garagehq.deuxfleurs.fr/). Unlike [Minio](https://min.io), Garage doesn't gracefully handle the …
> Don't set content-length header for HEAD requests with empty body

- .github/workflows/on-push.yml
- **tests: update elixir/erlang test matrix**
- **tests: use ubuntu 24.04**
Dropped unsupported elixir versions, added a couple missing ones, and the newest versions. Bumped the ubuntu version to the latest LTS.
> update tests, erlang 27, elixir 1.17, ubuntu 24.04

- lib/ex_aws/credentials_ini/file.ex
- test/ex_aws/credentials_ini/file_test.exs
Running `aws configure sso` produces a profile similar to
```
[profile mycompany]
sso_session = mycompanysso
sso_account_id = 111111111111
sso_role_name = ReadOnly
region = us-east-2
output = json
[sso-session mycompanysso]
sso_start_url = https://mycompanysso.awsapps.com/start
sso_region = us-east-1
sso_registration_scopes = sso:account:access
```
I'm pretty sure this
closes #951
> support sso credentials with profile in section name

- priv/endpoints.exs
Issue, demonstrated via comparing against us-gov-east-1 which works as desired:
Desire according to [aws documentation](https://aws.amazon.com/compliance/fips/#FIPS_Endpoints_by_Service):
This pull-request brings:
> Add/fix hostname of us-gov-west-1.

- priv/endpoints.exs
This allows `ExAws.Config.new(:codeartifact)` to run without throwing an error.
> Add Codeartifact to endpoints

- lib/ex_aws/request.ex
- priv/endpoints.exs
- test/ex_aws/request_test.exs
We want to be able to apply different retry strategies depending on the error type we get back from AWS.
More specifically:
1. We don't want to retry throughput exceeded errors to fail fast in case we temporarily overloaded AWS and bubble up the backpressure to the caller.
2. If AWS has some internal problems and returns 500 errors for a few seconds, we want to retry them.
This PR proposes a naive approach to enabling different `max_attempts` to be applied to the client errors (`400..499`).
A more sophisticated approach is to override the whole retry strategy (including backoff values) for specific errors or error ranges.
> Configurable max attempts for client errors

- lib/ex_aws/request/req.ex
Fixes the below deprecation warnings from Req:
```
warning: :follow_redirects option has been renamed to :redirect
(req 0.5.7) lib/req/steps.ex:1794: Req.Steps.redirect/1
(req 0.5.7) lib/req/request.ex:1120: anonymous fn/2 in Req.Request.run_response/2
(elixir 1.17.3) lib/enum.ex:4858: Enumerable.List.reduce/3
(elixir 1.17.3) lib/enum.ex:2585: Enum.reduce_while/3
(req 0.5.7) lib/req/request.ex:1047: Req.Request.run/1
(ex_aws 2.5.7) lib/ex_aws/request/req.ex:24: ExAws.Request.Req.request/5
```
`:follow_redirects` has been deprecated since `v0.4.0` per https://hexdocs.pm/req/changelog.html#v0-4-0-2023-09-01
> Fix Req :follow_redirects deprecation warning

- priv/endpoints.exs
Map the Bedrock Agent and Bedrock Agent Runtime endpoints. This allows to start using the services with the `ex_aws` library.
The PR is identical to the one which introduced endpoints for Bedrock and Bedrock Runtime: https://github.com/ex-aws/ex_aws/pull/1023.
The list of supported endpoints relies on
https://docs.aws.amazon.com/general/latest/gr/bedrock.html#bedrock_region.
> Add Bedrock Agent endpoints

- priv/endpoints.exs
Confirmation on the Dynamo region availability:
1. AWS regions for Dynamodb - https://docs.aws.amazon.com/general/latest/gr/ddb.html
2. Boto Core = https://github.com/boto/botocore/blob/d9d12af6e09ac587b506ec9f7a50082d0566f910/botocore/data/endpoints.json#L7494
Confirmation on the SQS region availability:
1. AWS regions for SQS - https://docs.aws.amazon.com/general/latest/gr/sqs-service.html#sqs_region
2. Boto Core - https://github.com/boto/botocore/blob/develop/botocore/data/endpoints.json#L22454
> Dynamodb, SQS, Firehose, Lambda endpoints for me-central -1

- .github/workflows/on-push.yml
- .tool-versions
List of changes:
- bump GitHub Actions and .tools-versions
- support Elixir 1.18 in matrix
- use major number and setup/beam will get latest version
> CI housekeeping

- priv/endpoints.exs
This pull request adds support for the AWS region eu-central-2 (Europe, Zurich) in the ExAws library. The eu-central-2 region was officially launched in 2022 and supports AWS CloudFormation. By incorporating this region, users can now utilize ExAws to manage AWS services within the Zurich region.​
CloudFormation is indeed supported in the eu-central-2 region: https://docs.aws.amazon.com/general/latest/gr/cfn.html
> Add eu-central-2 to CloudFormation endpoints

- lib/ex_aws/request.ex
- test/ex_aws/request_test.exs
Currently [retries](https://github.com/ex-aws/ex_aws/blob/main/lib/ex_aws/request.ex#L167) are only done for `ProvisionedThroughputExceededException` and `ThrottlingException`.
A few of the Cognito actions like [AdminCreateUser](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminCreateUser.html) and [AdminSetUserPassword](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminSetUserPassword.html) return `TooManyRequestsException` when the request limits are exceeded.
This PR contains fix to retry on `TooManyRequestsException`
> Implement retries for TooManyRequestsException 

- priv/endpoints.exs
Discovered that bedrock service was not included in the `aws-us-gov` partition of `endpoint.exs` when we got the error `bedrock-runtime not found in partition aws-us-gov`.
To resolve, copied the bedrock service definitions from the `AWS Standard` partition, replacing the standard region endpoints with gov ones. Also copied over the `fips` version of endpoints from the gov cloud dynamodb service definition, updating hostname to match the services to avoid this issue in the future if someone tries to use fips versions of he bedrock services.
Steps taken to verify PR:
- Tested usage of the `bedrock-runtime` in `us-gov-west-1` through successful usage of the converse stream api.  Operation:
```
%ExAws.Operation.JSON{
data: body,
headers: @json_request_headers,
http_method: :post,
path: …
```
> Add bedrock endpoints to gov cloud partition

- priv/endpoints.exs
Redshift data API is used for interacting with data in Redshift warehouse. The redshift endpoints are for infrastructure management instead. Adds capabilities to use Redshift Data API documented here: [redshift-data]
[redshift-data]: https://docs.aws.amazon.com/redshift-data/latest/APIReference/Welcome.html
> Add Redshift Data API endpoints

- lib/ex_aws/operation/s3.ex
- test/ex_aws/operation/s3_test.exs
> [!NOTE]
> I've written the code in this PR using Claude 4 and I reviewed the code afterwards.
When both `virtual_host=true` and `bucket_as_host=true` are configured, S3 URLs are incorrectly constructed with the bucket domain appearing twice.
For example:
- Expected: `https://my-bucket-domain.com/key`
- Actual: `https://my-bucket-domain.com/my-bucket-domain.com/key`
This affects all S3 operations when using custom domain buckets, including multipart uploads.
The `add_bucket_to_path` function in `ExAws.Operation.S3` only handled the `virtual_host` option but didn't support the `bucket_as_host` option. When `virtual_host=true`, it always constructed the hostname as `"#{bucket}.#{base_host}"`, even when `bucket_as_host=true` was set.
Added proper support for the `bucket_as_host` option by: …
> Fix bucket_as_host with virtual_host causing double bucket in URLs

- lib/ex_aws/config/defaults.ex
- priv/endpoints.exs
Fix constructing geo requests
Without this change when calling a location services API this message is returned from AWS: `{"message":"Credential should be scoped to correct service: 'geo-places'. "}`
Here's an example request that works after this change (that fails on `main`):
```elixir
operation =
%ExAws.Operation.JSON{
http_method: :post,
path: "/v2/suggest",
data: %{QueryText: "Elixir", BiasPosition: [157.8, 21.3]},
service: :places,
headers: []
}
ExAws.request(operation)
```
Also ensures that GovCloud supports places, currently was getting: `(RuntimeError) places not found in partition aws-us-gov`
Checklist:
> Fix geo operations

- priv/endpoints.exs
We need to have access to the SecretsManager secrets, and current version doesn't have our region in the list of supported ones.
> Add eu-north-1 to the list of support regions for AWS SecretsManager
